import { useState } from 'react'
import { Card, Typography, Button, Input, Space, message } from 'antd'
import { DownloadOutlined, FileTextOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import { ROUTES } from '../../utils/constants'

const { Title, Text } = Typography
const { TextArea } = Input

const COLS: Record<string, number> = {
  company_name: 0,
  status: 1,
  stage: 2,
  poc_name: 3,
  person_name: 4,
  mobile_number: 5,
  email_id: 6,
  lead_generation_date: 7,
  lead_generated_by: 8,
  contacted_date: 9,
  relevant: 10,
  city: 11,
  state: 12,
  industry: 13,
  no_of_divisions: 14,
  name_of_divisions: 15,
  designation_of_person: 16,
  company_description: 17,
  inventory_type_management_needed_for: 18,
  brochure_sent: 19,
  brochure_sent_date: 20,
  date_finalized: 21,
  demo_scheduled_date: 22,
  demo_scheduled_time: 23,
  people_attending: 24,
  roles_of_attendees: 25,
  attendees_emails: 26,
  attendees_mobile_no: 27,
  demo_status: 28,
  demo_date: 29,
  attendee_names: 30,
  video_recorded: 31,
  video_uploaded: 32,
  demo_duration: 33,
  interest_shown: 34,
  remark: -1,
}

function esc(s: string | null | undefined): string {
  if (s == null) return ''
  return String(s).replace(/'/g, "''").trim()
}

function parseDateDDMMYYYY(s: string): string | null {
  if (!s?.trim()) return null
  const m = s.trim().match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/)
  if (!m) return null
  const [, d, mo, y] = m
  return `${y}-${String(parseInt(mo!, 10)).padStart(2, '0')}-${String(parseInt(d!, 10)).padStart(2, '0')}`
}

function get(row: string[], col: number): string {
  const idx = col < 0 ? row.length + col : col
  if (idx >= 0 && idx < row.length && row[idx]?.trim()) return row[idx].trim()
  return ''
}

function buildJsonbPairs(pairs: [string, string][]): string {
  const parts = pairs.map(([k, v]) => `'${k}', '${esc(v)}'`)
  return `jsonb_build_object(${parts.join(', ')})`
}

function tsvToSql(tsvText: string): string {
  const lines = tsvText.trim().split(/\r?\n/).map((l) => l.trim()).filter(Boolean)
  const rows: string[][] = lines.map((line) => line.split('\t').map((c) => c.trim()))
  const c = COLS
  const sqlLines: string[] = [
    '-- Generated by Client to Lead → Import from sheet',
    '-- Run in Supabase SQL Editor. Requires public.user_profiles (full_name).',
    '',
    'CREATE SEQUENCE IF NOT EXISTS lead_import_ref_seq START 1;',
    '',
    'DO $$',
    'DECLARE',
    '  lid UUID;',
    '  ref_no TEXT;',
    '  lead_gen_ts TIMESTAMPTZ;',
    '  poc_id UUID;',
    'BEGIN',
  ]

  for (const row of rows) {
    if (row.length < 5) continue
    const company = get(row, c.company_name)
    if (!company) continue

    const status = get(row, c.status) || 'Open'
    const statusVal = status === 'Closed' ? 'Closed' : 'Open'
    const stage = get(row, c.stage) || 'Lead'
    const pocName = get(row, c.poc_name)
    const personName = get(row, c.person_name)
    const mobile = get(row, c.mobile_number)
    const email = get(row, c.email_id)
    const leadGenDate = parseDateDDMMYYYY(get(row, c.lead_generation_date))
    const leadGeneratedBy = get(row, c.lead_generated_by)
    const contactedDate = parseDateDDMMYYYY(get(row, c.contacted_date)) || leadGenDate
    const relevant = get(row, c.relevant)
    const city = get(row, c.city)
    const state = get(row, c.state)
    const industry = get(row, c.industry)
    const noDiv = get(row, c.no_of_divisions)
    const nameDiv = get(row, c.name_of_divisions)
    const designation = get(row, c.designation_of_person)
    const companyDesc = get(row, c.company_description)
    const invType = get(row, c.inventory_type_management_needed_for)
    const brochureSent = get(row, c.brochure_sent)
    const brochureDate = parseDateDDMMYYYY(get(row, c.brochure_sent_date))
    const dateFinalized = parseDateDDMMYYYY(get(row, c.date_finalized))
    const demoDateStr = parseDateDDMMYYYY(get(row, c.demo_scheduled_date))
    const demoTime = get(row, c.demo_scheduled_time)
    const demoDatetime = demoDateStr && demoTime ? `${demoDateStr} ${demoTime}` : (demoDateStr || '')
    const peopleAtt = get(row, c.people_attending)
    const rolesAtt = get(row, c.roles_of_attendees)
    const attEmails = get(row, c.attendees_emails)
    const attMobile = get(row, c.attendees_mobile_no)
    const demoStatus = get(row, c.demo_status)
    const demoDateDone = parseDateDDMMYYYY(get(row, c.demo_date))
    const attendeeNames = get(row, c.attendee_names)
    const videoRec = get(row, c.video_recorded)
    const videoUp = get(row, c.video_uploaded)
    const demoDur = get(row, c.demo_duration)
    const interest = get(row, c.interest_shown)
    const remark = get(row, c.remark)

    const leadGenTs = leadGenDate ? `to_timestamp('${leadGenDate}', 'YYYY-MM-DD')` : 'NOW()'

    sqlLines.push(`  -- ${company} | ${statusVal} | ${stage}`)
    sqlLines.push("  ref_no := 'IMP' || LPAD(nextval('lead_import_ref_seq')::text, 4, '0');")
    sqlLines.push(`  lead_gen_ts := ${leadGenTs};`)
    sqlLines.push('  poc_id := NULL;')
    if (pocName) sqlLines.push(`  SELECT id INTO poc_id FROM public.user_profiles WHERE full_name = '${esc(pocName)}' LIMIT 1;`)
    sqlLines.push('  INSERT INTO public.leads (company_name, stage, status, assigned_poc_id, reference_no, created_at)')
    sqlLines.push(`  VALUES ('${esc(company)}', '${esc(stage)}', '${esc(statusVal)}', poc_id, ref_no, lead_gen_ts)`)
    sqlLines.push('  RETURNING id INTO lid;')

    const leadDetailPairs: [string, string][] = [
      ['person_name', personName],
      ['mobile_number', mobile],
      ['email_id', email],
      ['lead_generation_date', leadGenDate || ''],
      ['lead_generated_by', leadGeneratedBy],
    ].filter(([, v]) => v) as [string, string][]
    if (leadDetailPairs.length) {
      sqlLines.push(`  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'lead_details', ${buildJsonbPairs(leadDetailPairs)});`)
    } else {
      sqlLines.push("  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'lead_details', '{}'::jsonb);")
    }

    const contactedPairs: [string, string][] = [
      ['contacted_date', contactedDate || ''],
      ['relevant', relevant],
      ['city', city],
      ['state', state],
      ['industry', industry],
      ['no_of_divisions', noDiv],
      ['name_of_divisions', nameDiv],
      ['designation_of_person', designation],
      ['company_description', companyDesc],
      ['inventory_type_management_needed_for', invType],
    ].filter(([, v]) => v) as [string, string][]
    if (contactedPairs.length) {
      sqlLines.push(`  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'contacted', ${buildJsonbPairs(contactedPairs)});`)
    } else {
      sqlLines.push("  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'contacted', '{}'::jsonb);")
    }

    const brochurePairs: [string, string][] = [
      ['brochure_sent', brochureSent],
      ['brochure_sent_date', brochureDate || ''],
    ].filter(([, v]) => v) as [string, string][]
    if (brochurePairs.length) {
      sqlLines.push(`  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'brochure', ${buildJsonbPairs(brochurePairs)});`)
    } else {
      sqlLines.push("  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'brochure', '{}'::jsonb);")
    }

    const demoSchedPairs: [string, string][] = [
      ['date_finalized', dateFinalized || ''],
      ['demo_scheduled_datetime', demoDatetime],
      ['people_attending', peopleAtt],
      ['roles_of_attendees', rolesAtt],
      ['attendees_emails', attEmails],
      ['attendees_mobile_no', attMobile],
    ].filter(([, v]) => v) as [string, string][]
    if (demoSchedPairs.length) {
      sqlLines.push(`  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'demo_schedule', ${buildJsonbPairs(demoSchedPairs)});`)
    } else {
      sqlLines.push("  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'demo_schedule', '{}'::jsonb);")
    }

    const demoDonePairs: [string, string][] = [
      ['demo_status', demoStatus],
      ['demo_date', demoDateDone || ''],
      ['attendee_names', attendeeNames],
      ['video_recorded', videoRec],
      ['video_uploaded', videoUp],
      ['demo_duration', demoDur],
      ['interest_shown', interest],
    ].filter(([, v]) => v) as [string, string][]
    if (demoDonePairs.length) {
      sqlLines.push(`  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'demo_completed', ${buildJsonbPairs(demoDonePairs)});`)
    } else {
      sqlLines.push("  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'demo_completed', '{}'::jsonb);")
    }

    for (const slug of ['offer_letter', 'po', 'performa_invoice', 'implementation_invoice', 'whatsapp_group', 'setup_data', 'account_setup', 'item_setup', 'first_invoice', 'first_invoice_payment']) {
      sqlLines.push(`  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, '${slug}', '{}'::jsonb);`)
    }

    if (remark) {
      sqlLines.push(`  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'final_closing', jsonb_build_object('remark', '${esc(remark)}'));`)
    } else {
      sqlLines.push("  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'final_closing', '{}'::jsonb);")
    }
    sqlLines.push('')
  }

  sqlLines.push('END $$;')
  return sqlLines.join('\n')
}

function downloadSql(sql: string, filename: string) {
  const blob = new Blob([sql], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export const LeadImportPage = () => {
  const navigate = useNavigate()
  const [tsv, setTsv] = useState('')
  const [generating, setGenerating] = useState(false)

  const handleGenerate = () => {
    const trimmed = tsv.trim()
    if (!trimmed) {
      message.warning('Paste your tab-separated sheet data first.')
      return
    }
    setGenerating(true)
    try {
      const sql = tsvToSql(trimmed)
      const lines = trimmed.split(/\r?\n/).filter((l) => l.trim())
      const rowCount = lines.filter((l) => l.split('\t').length >= 5).length
      downloadSql(sql, `IMPORT_LEADS_${new Date().toISOString().slice(0, 10)}.sql`)
      message.success(`Generated SQL for ${rowCount} lead(s). File downloaded. Run it in Supabase SQL Editor.`)
    } catch (e) {
      message.error('Failed to generate SQL. Check that data is tab-separated.')
    } finally {
      setGenerating(false)
    }
  }

  return (
    <div style={{ padding: 24 }}>
      <Space style={{ marginBottom: 16 }} wrap>
        <Button type="text" onClick={() => navigate(ROUTES.LEADS)}>
          ← Back to Lead
        </Button>
      </Space>
      <Card>
        <Space direction="vertical" size="middle" style={{ width: '100%' }}>
          <Title level={4} style={{ margin: 0 }}>
            <FileTextOutlined /> Import from sheet – Generate SQL
          </Title>
          <Text type="secondary">
            Paste your tab-separated data (e.g. from Excel: copy rows, paste here). Column order: Company, Status, Stage, POC, Person Name, Mobile, Email, Lead Gen Date, … Remark (last column). Then click Generate to download the SQL file. Run the file in Supabase SQL Editor to import leads with Person Name, City, State etc. filled.
          </Text>
          <TextArea
            placeholder="Paste tab-separated rows here (Company Name	Status	Stage	POC	Person Name	Mobile	...	Remark)"
            value={tsv}
            onChange={(e) => setTsv(e.target.value)}
            rows={12}
            style={{ fontFamily: 'monospace', fontSize: 12 }}
          />
          <Space>
            <Button
              type="primary"
              icon={<DownloadOutlined />}
              onClick={handleGenerate}
              loading={generating}
            >
              Generate & download SQL
            </Button>
          </Space>
        </Space>
      </Card>
    </div>
  )
}
