import { useState } from 'react'
import { Card, Typography, Button, Input, Space, message } from 'antd'
import { DownloadOutlined, FileTextOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import { ROUTES } from '../../utils/constants'

const { Title, Text } = Typography
const { TextArea } = Input

/**
 * Full sheet layout (74 columns, 0-based indices).
 * Row 1 can be section headers — rows where column 0 = "Company Name" are skipped.
 * Paste from Excel: header row + data rows, tab-separated.
 */
const COLS = {
  company_name: 0,
  status: 1,
  stage: 2,
  poc_name: 3,
  person_name: 4,
  mobile_number: 5,
  email_id: 6,
  lead_generation_date: 7,
  lead_generated_by: 8,
  contacted_date: 9,
  relevant: 10,
  city: 11,
  state: 12,
  industry: 13,
  no_of_divisions: 14,
  name_of_divisions: 15,
  designation_of_person: 16,
  company_description: 17,
  inventory_type_management_needed_for: 18,
  brochure_sent: 19,
  brochure_sent_date: 20,
  date_finalized: 21,
  demo_scheduled_date: 22,
  demo_scheduled_time: 23,
  people_attending: 24,
  roles_of_attendees: 25,
  attendees_emails: 26,
  attendees_mobile_no: 27,
  demo_status: 28,
  demo_date: 29,
  demo_conducted_by: 30,
  attendee_names: 31,
  video_recorded: 32,
  video_uploaded: 33,
  demo_duration: 34,
  interest_shown: 35,
  google_form_sent: 36,
  google_form_sent_date: 37,
  google_form_filled: 38,
  google_form_filled_date: 39,
  offer_letter_sent: 40,
  offer_letter_sent_date: 41,
  offer_letter_approved: 42,
  offer_letter_approved_date: 43,
  po_format_sent: 44,
  po_format_sent_date: 45,
  po_received: 46,
  po_received_date: 47,
  performa_invoice_sent: 48,
  performa_invoice_sent_date: 49,
  payment_received: 50,
  payment_received_date: 51,
  implementation_invoice_sent: 52,
  implementation_date_sent: 53,
  whatsapp_group_created: 54,
  date_created_on_whatsapp: 55,
  setup_details_sent: 56,
  setup_sent_date: 57,
  received_setup_data: 58,
  account_date_received: 59,
  uploaded_on_portal_account: 60,
  account_uploaded_date: 61,
  received_item_data: 62,
  item_date_received: 63,
  uploaded_on_portal_item_2: 64,
  item_upload_date_2: 65,
  training_start_date: 66,
  training_end_date: 67,
  f_status: 68,
  invoice_raised: 69,
  invoice_generated_date: 70,
  final_payment_received: 71,
  final_payment_received_date: 72,
  last_contacted_on: 73,
} as const

function esc(s: string | null | undefined): string {
  if (s == null) return ''
  return String(s).replace(/'/g, "''").trim()
}

function parseDateDDMMYYYY(s: string): string | null {
  if (!s?.trim()) return null
  const m = s.trim().match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/)
  if (!m) return null
  const [, d, mo, y] = m
  return `${y}-${String(parseInt(mo!, 10)).padStart(2, '0')}-${String(parseInt(d!, 10)).padStart(2, '0')}`
}

function get(row: string[], col: number): string {
  if (col < 0 || col >= row.length) return ''
  const v = row[col]
  if (v == null) return ''
  return String(v).trim()
}

function buildJsonbPairs(pairs: [string, string][]): string {
  const parts = pairs.map(([k, v]) => `'${k}', '${esc(v)}'`)
  return `jsonb_build_object(${parts.join(', ')})`
}

function stageLine(slug: string, pairs: [string, string][]): string {
  const filtered = pairs.filter(([, v]) => v !== '')
  if (filtered.length === 0) {
    return `  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, '${slug}', '{}'::jsonb);`
  }
  return `  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, '${slug}', ${buildJsonbPairs(filtered)});`
}

function tsvToSql(tsvText: string): string {
  const lines = tsvText.trim().split(/\r?\n/).map((l) => l.trim()).filter(Boolean)
  const rows: string[][] = lines.map((line) => line.split('\t').map((c) => c.trim()))
  const c = COLS
  const sqlLines: string[] = [
    '-- Generated by Client to Lead → Import from sheet (full 74-column layout)',
    '-- Run in Supabase SQL Editor. Requires public.user_profiles (full_name) for POC match.',
    '',
    'CREATE SEQUENCE IF NOT EXISTS lead_import_ref_seq START 1;',
    '',
    'DO $$',
    'DECLARE',
    '  lid UUID;',
    '  ref_no TEXT;',
    '  lead_gen_ts TIMESTAMPTZ;',
    '  poc_id UUID;',
    'BEGIN',
  ]

  for (const row of rows) {
    const headerProbe = get(row, c.company_name)
    if (headerProbe === 'Company Name') continue

    if (row.length < 5) continue
    const company = get(row, c.company_name)
    if (!company || company.length < 2) continue

    const status = get(row, c.status) || 'Open'
    const statusVal = status === 'Closed' ? 'Closed' : 'Open'
    const stage = get(row, c.stage) || 'Lead'
    const pocName = get(row, c.poc_name)
    const personName = get(row, c.person_name)
    const mobile = get(row, c.mobile_number)
    const email = get(row, c.email_id)
    const leadGenDate = parseDateDDMMYYYY(get(row, c.lead_generation_date))
    const leadGeneratedBy = get(row, c.lead_generated_by)
    const contactedDate = parseDateDDMMYYYY(get(row, c.contacted_date)) || leadGenDate
    const relevant = get(row, c.relevant)
    const city = get(row, c.city)
    const state = get(row, c.state)
    const industry = get(row, c.industry)
    const noDiv = get(row, c.no_of_divisions)
    const nameDiv = get(row, c.name_of_divisions)
    const designation = get(row, c.designation_of_person)
    const companyDesc = get(row, c.company_description)
    const invType = get(row, c.inventory_type_management_needed_for)
    const brochureSent = get(row, c.brochure_sent)
    const brochureDate = parseDateDDMMYYYY(get(row, c.brochure_sent_date))
    const dateFinalized = parseDateDDMMYYYY(get(row, c.date_finalized))
    const demoDateStr = parseDateDDMMYYYY(get(row, c.demo_scheduled_date))
    const demoTime = get(row, c.demo_scheduled_time)
    const demoDatetime = demoDateStr && demoTime ? `${demoDateStr} ${demoTime}` : demoDateStr || ''
    const peopleAtt = get(row, c.people_attending)
    const rolesAtt = get(row, c.roles_of_attendees)
    const attEmails = get(row, c.attendees_emails)
    const attMobile = get(row, c.attendees_mobile_no)
    const demoStatus = get(row, c.demo_status)
    const demoDateDone = parseDateDDMMYYYY(get(row, c.demo_date))
    const demoConductedBy = get(row, c.demo_conducted_by)
    const attendeeNames = get(row, c.attendee_names)
    const videoRec = get(row, c.video_recorded)
    const videoUp = get(row, c.video_uploaded)
    const demoDur = get(row, c.demo_duration)
    const interest = get(row, c.interest_shown)

    const googleSent = get(row, c.google_form_sent)
    const googleSentDate = parseDateDDMMYYYY(get(row, c.google_form_sent_date))
    const googleFilled = get(row, c.google_form_filled)
    const googleFilledDate = parseDateDDMMYYYY(get(row, c.google_form_filled_date))

    const offerSent = get(row, c.offer_letter_sent)
    const offerSentDate = parseDateDDMMYYYY(get(row, c.offer_letter_sent_date))
    const offerAppr = get(row, c.offer_letter_approved)
    const offerApprDate = parseDateDDMMYYYY(get(row, c.offer_letter_approved_date))

    const poFmtSent = get(row, c.po_format_sent)
    const poFmtDate = parseDateDDMMYYYY(get(row, c.po_format_sent_date))
    const poRec = get(row, c.po_received)
    const poRecDate = parseDateDDMMYYYY(get(row, c.po_received_date))

    const perfSent = get(row, c.performa_invoice_sent)
    const perfDate = parseDateDDMMYYYY(get(row, c.performa_invoice_sent_date))
    const payRec = get(row, c.payment_received)
    const payRecDate = parseDateDDMMYYYY(get(row, c.payment_received_date))

    const implSent = get(row, c.implementation_invoice_sent)
    const implDateSent = parseDateDDMMYYYY(get(row, c.implementation_date_sent))

    const waCreated = get(row, c.whatsapp_group_created)
    const waDate = parseDateDDMMYYYY(get(row, c.date_created_on_whatsapp))

    const setupSent = get(row, c.setup_details_sent)
    const setupSentDate = parseDateDDMMYYYY(get(row, c.setup_sent_date))

    const recvSetup = get(row, c.received_setup_data)
    const accDateRecv = parseDateDDMMYYYY(get(row, c.account_date_received))
    const upPortal = get(row, c.uploaded_on_portal_account)
    const accUpDate = parseDateDDMMYYYY(get(row, c.account_uploaded_date))

    const recvItem = get(row, c.received_item_data)
    const itemDateRecv = parseDateDDMMYYYY(get(row, c.item_date_received))
    const upPortal2 = get(row, c.uploaded_on_portal_item_2)
    const itemUp2 = parseDateDDMMYYYY(get(row, c.item_upload_date_2))

    const trainStart = parseDateDDMMYYYY(get(row, c.training_start_date))
    const trainEnd = parseDateDDMMYYYY(get(row, c.training_end_date))
    const fStat = get(row, c.f_status)

    const invRaised = get(row, c.invoice_raised)
    const invGenDate = parseDateDDMMYYYY(get(row, c.invoice_generated_date))
    const finalPay = get(row, c.final_payment_received)
    const finalPayDate = parseDateDDMMYYYY(get(row, c.final_payment_received_date))
    const lastContact = parseDateDDMMYYYY(get(row, c.last_contacted_on))

    const leadGenTs = leadGenDate ? `to_timestamp('${leadGenDate}', 'YYYY-MM-DD')` : 'NOW()'

    sqlLines.push(`  -- ${company} | ${statusVal} | ${stage}`)
    sqlLines.push("  ref_no := 'IMP' || LPAD(nextval('lead_import_ref_seq')::text, 4, '0');")
    sqlLines.push(`  lead_gen_ts := ${leadGenTs};`)
    sqlLines.push('  poc_id := NULL;')
    if (pocName) sqlLines.push(`  SELECT id INTO poc_id FROM public.user_profiles WHERE full_name = '${esc(pocName)}' LIMIT 1;`)
    sqlLines.push('  INSERT INTO public.leads (company_name, stage, status, assigned_poc_id, reference_no, created_at)')
    sqlLines.push(`  VALUES ('${esc(company)}', '${esc(stage)}', '${esc(statusVal)}', poc_id, ref_no, lead_gen_ts)`)
    sqlLines.push('  RETURNING id INTO lid;')

    sqlLines.push(
      stageLine('lead_details', [
        ['person_name', personName],
        ['mobile_number', mobile],
        ['email_id', email],
        ['lead_generation_date', leadGenDate || ''],
        ['lead_generated_by', leadGeneratedBy],
      ])
    )

    sqlLines.push(
      stageLine('contacted', [
        ['contacted_date', contactedDate || ''],
        ['relevant', relevant],
        ['city', city],
        ['state', state],
        ['industry', industry],
        ['no_of_divisions', noDiv],
        ['name_of_divisions', nameDiv],
        ['designation_of_person', designation],
        ['company_description', companyDesc],
        ['inventory_type_management_needed_for', invType],
      ])
    )

    sqlLines.push(
      stageLine('brochure', [
        ['brochure_sent', brochureSent],
        ['brochure_sent_date', brochureDate || ''],
      ])
    )

    sqlLines.push(
      stageLine('demo_schedule', [
        ['date_finalized', dateFinalized || ''],
        ['demo_scheduled_datetime', demoDatetime],
        ['people_attending', peopleAtt],
        ['roles_of_attendees', rolesAtt],
        ['attendees_emails', attEmails],
        ['attendees_mobile_no', attMobile],
      ])
    )

    sqlLines.push(
      stageLine('demo_completed', [
        ['demo_status', demoStatus],
        ['demo_date', demoDateDone || ''],
        ['demo_conducted_by', demoConductedBy],
        ['attendee_names', attendeeNames],
        ['video_recorded', videoRec],
        ['video_uploaded', videoUp],
        ['demo_duration', demoDur],
        ['interest_shown', interest],
      ])
    )

    sqlLines.push(
      stageLine('google_form', [
        ['google_form_sent', googleSent],
        ['google_form_sent_date', googleSentDate || ''],
        ['google_form_filled', googleFilled],
        ['google_form_filled_date', googleFilledDate || ''],
      ])
    )

    sqlLines.push(
      stageLine('offer_letter', [
        ['offer_letter_sent', offerSent],
        ['offer_letter_sent_date', offerSentDate || ''],
        ['offer_letter_approved', offerAppr],
        ['offer_letter_approved_date', offerApprDate || ''],
      ])
    )

    sqlLines.push(
      stageLine('po', [
        ['po_format_sent', poFmtSent],
        ['po_format_sent_date', poFmtDate || ''],
        ['po_received', poRec],
        ['po_received_date', poRecDate || ''],
      ])
    )

    sqlLines.push(
      stageLine('performa_invoice', [
        ['performa_invoice_sent', perfSent],
        ['performa_invoice_sent_date', perfDate || ''],
        ['payment_received', payRec],
        ['payment_received_date', payRecDate || ''],
      ])
    )

    sqlLines.push(
      stageLine('implementation_invoice', [
        ['implementation_invoice_sent', implSent],
        ['date_sent', implDateSent || ''],
      ])
    )

    sqlLines.push(
      stageLine('whatsapp_group', [
        ['whatsapp_group_created', waCreated],
        ['date_created_on', waDate || ''],
      ])
    )

    sqlLines.push(
      stageLine('setup_data', [
        ['setup_details_sent', setupSent],
        ['sent_date', setupSentDate || ''],
      ])
    )

    sqlLines.push(
      stageLine('account_setup', [
        ['received_setup_data', recvSetup],
        ['date_received', accDateRecv || ''],
        ['uploaded_on_portal', upPortal],
        ['uploaded_date', accUpDate || ''],
      ])
    )

    sqlLines.push(
      stageLine('item_setup', [
        ['received_item_data', recvItem],
        ['date_received', itemDateRecv || ''],
        ['uploaded_on_portal', upPortal2],
        ['upload_date', itemUp2 || ''],
      ])
    )

    sqlLines.push(
      stageLine('training_stage', [
        ['start_date', trainStart || ''],
        ['end_date', trainEnd || ''],
        ['f_status', fStat],
      ])
    )

    sqlLines.push(
      stageLine('first_invoice', [
        ['invoice_raised', invRaised],
        ['invoice_generated_date', invGenDate || ''],
      ])
    )

    sqlLines.push(
      stageLine('first_invoice_payment', [
        ['final_payment_received', finalPay],
        ['final_payment_received_date', finalPayDate || ''],
      ])
    )

    const finalPairs: [string, string][] = []
    if (lastContact) finalPairs.push(['last_contact_date', lastContact])
    if (finalPairs.length) {
      sqlLines.push(`  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'final_closing', ${buildJsonbPairs(finalPairs)});`)
    } else {
      sqlLines.push("  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'final_closing', '{}'::jsonb);")
    }

    sqlLines.push('')
  }

  sqlLines.push('END $$;')
  return sqlLines.join('\n')
}

function downloadSql(sql: string, filename: string) {
  const blob = new Blob([sql], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export const LeadImportPage = () => {
  const navigate = useNavigate()
  const [tsv, setTsv] = useState('')
  const [generating, setGenerating] = useState(false)

  const handleGenerate = () => {
    const trimmed = tsv.trim()
    if (!trimmed) {
      message.warning('Paste your tab-separated sheet data first.')
      return
    }
    setGenerating(true)
    try {
      const sql = tsvToSql(trimmed)
      const lines = trimmed.split(/\r?\n/).filter((l) => l.trim())
      const rowCount = lines.filter((l) => {
        const p = l.split('\t')[0]?.trim()
        return p && p !== 'Company Name' && l.split('\t').length >= 5
      }).length
      downloadSql(sql, `IMPORT_LEADS_FULL_${new Date().toISOString().slice(0, 10)}.sql`)
      message.success(`Generated SQL for ${rowCount} lead row(s). Run the file in Supabase SQL Editor.`)
    } catch (e) {
      message.error('Failed to generate SQL. Check that data is tab-separated with 74 columns.')
    } finally {
      setGenerating(false)
    }
  }

  return (
    <div style={{ padding: 24 }}>
      <Space style={{ marginBottom: 16 }} wrap>
        <Button type="text" onClick={() => navigate(ROUTES.LEADS)}>
          ← Back to Lead
        </Button>
      </Space>
      <Card>
        <Space direction="vertical" size="middle" style={{ width: '100%' }}>
          <Title level={4} style={{ margin: 0 }}>
            <FileTextOutlined /> Import from sheet – Generate SQL (full columns)
          </Title>
          <Text type="secondary">
            Paste tab-separated data from Excel: include the header row (Company Name, Status, … Last Contacted On), then data
            rows. The generator maps all 74 columns into <code>lead_stage_data</code> (Lead → Final Closing). Rows where column A
            is &quot;Company Name&quot; are skipped. POC must match <code>user_profiles.full_name</code> exactly.
          </Text>
          <TextArea
            placeholder="Paste TSV here (header + rows, 74 columns)…"
            value={tsv}
            onChange={(e) => setTsv(e.target.value)}
            rows={12}
            style={{ fontFamily: 'monospace', fontSize: 12 }}
          />
          <Space>
            <Button
              type="primary"
              icon={<DownloadOutlined />}
              onClick={handleGenerate}
              loading={generating}
            >
              Generate & download SQL
            </Button>
          </Space>
        </Space>
      </Card>
    </div>
  )
}
