import { Form, Input, DatePicker, Select, InputNumber } from 'antd'
import dayjs from 'dayjs'

/** Stage slug -> list of field configs for the form */
export const STAGE_FIELDS: Record<
  string,
  { name: string; label: string; type: string; maxLength?: number; options?: { label: string; value: string }[] }[]
> = {
  lead_details: [
    { name: 'person_name', label: 'Person Name', type: 'text' },
    { name: 'mobile_number', label: 'Mobile Number', type: 'number', maxLength: 10 },
    { name: 'email_id', label: 'Email ID', type: 'text', maxLength: 30 },
    { name: 'lead_generation_date', label: 'Lead Generation Date', type: 'date' },
    { name: 'lead_generated_by', label: 'Lead Generated By', type: 'text' },
  ],
  contacted: [
    { name: 'contacted_date', label: 'Contacted Date', type: 'date' },
    { name: 'relevant', label: 'Relevant?', type: 'text' },
    { name: 'city', label: 'City', type: 'text' },
    { name: 'state', label: 'State', type: 'text' },
    { name: 'industry', label: 'Industry', type: 'text' },
    { name: 'no_of_divisions', label: 'No of Divisions', type: 'text' },
    { name: 'name_of_divisions', label: 'Name of Divisions', type: 'text' },
    { name: 'designation_of_person', label: 'Designation of Person', type: 'text' },
    { name: 'company_description', label: 'Company Description', type: 'textarea' },
    { name: 'inventory_type_management_needed_for', label: 'Inventory Type Management Needed For?', type: 'text' },
  ],
  brochure: [
    { name: 'brochure_sent', label: 'Brochure Sent?', type: 'select', options: [{ label: 'Yes', value: 'Yes' }, { label: 'No', value: 'No' }] },
    { name: 'brochure_sent_date', label: 'Brochure Sent Date', type: 'date' },
  ],
  demo_schedule: [
    { name: 'date_finalized', label: 'Date on which Demo Schedule was finalized', type: 'date' },
    { name: 'demo_scheduled_datetime', label: 'Demo Scheduled Date & Time', type: 'datetime' },
    { name: 'people_attending', label: 'People Attending', type: 'text' },
    { name: 'roles_of_attendees', label: 'Roles of Attendees', type: 'text' },
    { name: 'attendees_emails', label: 'Attendees Emails', type: 'text' },
    { name: 'attendees_mobile_no', label: 'Attendees Mobile No', type: 'number', maxLength: 10 },
  ],
  demo_completed: [
    { name: 'demo_status', label: 'Demo Status', type: 'select', options: [{ label: 'Done', value: 'Done' }, { label: 'Not Done', value: 'Not Done' }] },
    { name: 'demo_date', label: 'Demo Date', type: 'date' },
    { name: 'demo_conducted_by', label: 'Demo Conducted By', type: 'text' },
    { name: 'attendee_names', label: 'Attendee Names', type: 'text' },
    { name: 'video_recorded', label: 'Video Recorded', type: 'select', options: [{ label: 'Yes', value: 'Yes' }, { label: 'No', value: 'No' }] },
    { name: 'video_uploaded', label: 'Video Uploaded', type: 'select', options: [{ label: 'Yes', value: 'Yes' }, { label: 'No', value: 'No' }] },
    { name: 'demo_duration', label: 'Demo Duration', type: 'text' },
    { name: 'interest_shown', label: 'Interest Shown', type: 'text' },
  ],
  google_form: [
    { name: 'google_form_sent', label: 'Google Form Sent?', type: 'select', options: [{ label: 'Yes', value: 'Yes' }, { label: 'No', value: 'No' }] },
    { name: 'google_form_sent_date', label: 'Google Form Sent Date', type: 'date' },
    { name: 'google_form_filled', label: 'Google Form Filled', type: 'text' },
    { name: 'google_form_filled_date', label: 'Google Form Filled Date', type: 'date' },
  ],
  offer_letter: [
    { name: 'offer_letter_sent', label: 'Offer Letter Sent?', type: 'select', options: [{ label: 'Yes', value: 'Yes' }, { label: 'No', value: 'No' }] },
    { name: 'offer_letter_sent_date', label: 'Offer Letter Sent Date', type: 'date' },
    { name: 'offer_letter_approved', label: 'Offer Letter Approved?', type: 'select', options: [{ label: 'Yes', value: 'Yes' }, { label: 'No', value: 'No' }] },
    { name: 'offer_letter_approved_date', label: 'Offer Letter Approved Date', type: 'date' },
  ],
  po: [
    { name: 'po_format_sent', label: 'PO Format Sent?', type: 'select', options: [{ label: 'Yes', value: 'Yes' }, { label: 'No', value: 'No' }] },
    { name: 'po_format_sent_date', label: 'PO Format Sent Date', type: 'date' },
    { name: 'po_received', label: 'PO Received?', type: 'select', options: [{ label: 'Yes', value: 'Yes' }, { label: 'No', value: 'No' }] },
    { name: 'po_received_date', label: 'PO Received Date', type: 'date' },
  ],
  performa_invoice: [
    { name: 'performa_invoice_sent', label: 'Performa Invoice Sent?', type: 'select', options: [{ label: 'Yes', value: 'Yes' }, { label: 'No', value: 'No' }] },
    { name: 'performa_invoice_sent_date', label: 'Performa Invoice Sent Date', type: 'date' },
    { name: 'payment_received', label: 'Payment Received?', type: 'select', options: [{ label: 'Yes', value: 'Yes' }, { label: 'No', value: 'No' }] },
    { name: 'payment_received_date', label: 'Payment Received Date', type: 'date' },
  ],
  implementation_invoice: [
    { name: 'implementation_invoice_sent', label: 'Implementation Invoice Sent?', type: 'select', options: [{ label: 'Yes', value: 'Yes' }, { label: 'No', value: 'No' }] },
    { name: 'date_sent', label: 'Date Sent', type: 'date' },
  ],
  whatsapp_group: [
    { name: 'whatsapp_group_created', label: 'WhatsApp Group Created?', type: 'select', options: [{ label: 'Yes', value: 'Yes' }, { label: 'No', value: 'No' }] },
    { name: 'date_created_on', label: 'Date Created On', type: 'date' },
  ],
  setup_data: [
    { name: 'setup_details_sent', label: 'Setup Details Sent?', type: 'select', options: [{ label: 'Yes', value: 'Yes' }, { label: 'No', value: 'No' }] },
    { name: 'sent_date', label: 'Sent Date', type: 'date' },
  ],
  account_setup: [
    { name: 'received_setup_data', label: 'Received Setup Data?', type: 'select', options: [{ label: 'Yes', value: 'Yes' }, { label: 'No', value: 'No' }] },
    { name: 'date_received', label: 'Date Received', type: 'date' },
    { name: 'uploaded_on_portal', label: 'Uploaded on Portal?', type: 'select', options: [{ label: 'Yes', value: 'Yes' }, { label: 'No', value: 'No' }] },
    { name: 'uploaded_date', label: 'Uploaded Date', type: 'date' },
  ],
  item_setup: [
    { name: 'received_item_data', label: 'Received Item Data?', type: 'select', options: [{ label: 'Yes', value: 'Yes' }, { label: 'No', value: 'No' }] },
    { name: 'date_received', label: 'Date Received', type: 'date' },
    { name: 'uploaded_on_portal', label: 'Uploaded on Portal?', type: 'select', options: [{ label: 'Yes', value: 'Yes' }, { label: 'No', value: 'No' }] },
    { name: 'upload_date', label: 'Upload Date', type: 'date' },
  ],
  training_stage: [
    { name: 'start_date', label: 'Start Date', type: 'date' },
    { name: 'end_date', label: 'End Date', type: 'date' },
    { name: 'f_status', label: 'FStatus', type: 'text' },
  ],
  first_invoice: [
    { name: 'invoice_raised', label: 'Invoice Raised?', type: 'select', options: [{ label: 'Yes', value: 'Yes' }, { label: 'No', value: 'No' }] },
    { name: 'invoice_generated_date', label: 'Invoice Generated Date', type: 'date' },
  ],
  first_invoice_payment: [
    { name: 'final_payment_received', label: 'Final Payment Received?', type: 'select', options: [{ label: 'Yes', value: 'Yes' }, { label: 'No', value: 'No' }] },
    { name: 'final_payment_received_date', label: 'Final Payment Received Date', type: 'date' },
  ],
  final_closing: [
    { name: 'last_contact_date', label: 'Last Contacted On', type: 'date' },
    { name: 'remark', label: 'Remark', type: 'textarea' },
  ],
}

function serializeValue(val: unknown): string | number | null {
  if (val == null) return null as unknown as string
  if (dayjs.isDayjs(val)) return val.format('YYYY-MM-DD')
  if (typeof val === 'object' && val !== null && 'format' in val && typeof (val as { format: (s: string) => string }).format === 'function')
    return (val as { format: (s: string) => string }).format('YYYY-MM-DD HH:mm')
  return val as string | number
}

export function getStageFormValuesForPayload(values: Record<string, unknown>, stageSlug: string): Record<string, unknown> {
  const fields = STAGE_FIELDS[stageSlug] || []
  const out: Record<string, unknown> = {}
  for (const f of fields) {
    const v = values[f.name]
    if (f.type === 'date' || f.type === 'datetime') out[f.name] = serializeValue(v)
    else out[f.name] = v
  }
  return out
}

export function getInitialValuesFromData(data: Record<string, unknown> | undefined, stageSlug: string): Record<string, unknown> {
  if (!data) return {}
  const fields = STAGE_FIELDS[stageSlug] || []
  const out: Record<string, unknown> = {}
  for (const f of fields) {
    const v = data[f.name]
    if (v == null) continue
    if (f.type === 'date' && typeof v === 'string') out[f.name] = dayjs(v)
    else if (f.type === 'datetime' && typeof v === 'string') out[f.name] = dayjs(v)
    else out[f.name] = v
  }
  return out
}

function formatDisplayValue(v: unknown, type: string): string {
  if (v == null || v === '') return '—'
  if (type === 'date' && typeof v === 'string') return dayjs(v).isValid() ? dayjs(v).format('DD MMM YYYY') : String(v)
  if (type === 'datetime' && typeof v === 'string') return dayjs(v).isValid() ? dayjs(v).format('DD MMM YYYY HH:mm') : String(v)
  return String(v)
}

/** For read-only display: list of { label, value } for a stage's data (Support-style sections) */
export function getStageDisplayItems(
  stageSlug: string,
  data: Record<string, unknown> | undefined
): { label: string; value: string }[] {
  if (!data) return []
  const fields = STAGE_FIELDS[stageSlug] || []
  return fields.map((f) => ({
    label: f.label,
    value: formatDisplayValue(data[f.name], f.type),
  }))
}

export function renderStageFormItems(
  stageSlug: string,
  formItemLayout: { labelCol?: object; wrapperCol?: object } = {}
) {
  const fields = STAGE_FIELDS[stageSlug] || []
  return fields.map((f) => {
    if (f.type === 'select')
      return (
        <Form.Item key={f.name} name={f.name} label={f.label} {...formItemLayout}>
          <Select placeholder={`Select ${f.label}`} options={f.options} allowClear />
        </Form.Item>
      )
    if (f.type === 'date')
      return (
        <Form.Item key={f.name} name={f.name} label={f.label} {...formItemLayout}>
          <DatePicker style={{ width: '100%' }} format="YYYY-MM-DD" />
        </Form.Item>
      )
    if (f.type === 'datetime')
      return (
        <Form.Item key={f.name} name={f.name} label={f.label} {...formItemLayout}>
          <DatePicker showTime style={{ width: '100%' }} format="YYYY-MM-DD HH:mm" />
        </Form.Item>
      )
    if (f.type === 'number')
      return (
        <Form.Item key={f.name} name={f.name} label={f.label} {...formItemLayout}>
          <InputNumber style={{ width: '100%' }} maxLength={f.maxLength || 10} controls={false} />
        </Form.Item>
      )
    if (f.type === 'textarea')
      return (
        <Form.Item key={f.name} name={f.name} label={f.label} {...formItemLayout}>
          <Input.TextArea rows={4} />
        </Form.Item>
      )
    return (
      <Form.Item key={f.name} name={f.name} label={f.label} {...formItemLayout}>
        <Input maxLength={f.maxLength} />
      </Form.Item>
    )
  })
}
