-- =============================================================================
-- DEPRECATED — in-app email scheduler removed from the application.
-- Run database/DROP_EMAIL_JOB_SCHEDULES.sql in Supabase to drop the table.
-- Use database/CRON_JOB_ORG_SETUP.md for cron-job.org URLs instead.
-- =============================================================================
