-- ============================================================================
-- STEP 1: Bulk upload Feature tickets from your data
-- ============================================================================
-- Workflow:
--   1. Run this script (FEATURE_TICKETS_BULK_UPLOAD.sql) first
--   2. Then run FIX_FE_TICKETS_BULK_WITH_IDS.sql
--   3. Then run FIX_FE_TICKETS_COMPANY_BY_REF.sql (to fix company names)
--
-- Uses ON CONFLICT (reference_no) DO NOTHING - skips rows that would conflict.
-- (DO UPDATE can fail with "cannot affect row a second time" if any duplicate
--  reference_no exists within the same INSERT.)
--
-- Requires: public.companies, public.pages, public.user_profiles have at least one row.
-- Rows without reference_no get auto-generated FE-xxxx. Rows with FE-0001, etc. are upserted.
-- ============================================================================

INSERT INTO public.tickets (
  reference_no, title, description, type, status, priority,
  company_id, division_id, created_by, created_at, updated_at,
  attachment_url, page, page_id, company_name, division, division_other, user_name,
  communicated_through, submitted_by, query_arrival_at,
  approval_status
) VALUES
  (NULL, 'Issue posting karte samay rate or amount dikhana chahiye', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2024-10-01 11:18:54+00', NOW(), 'https://drive.google.com/open?id=1N1U21AWPfIVmsllZSknnVp4l-F_CcOo0', 'Issue', NULL, 'Nutan Ispat & Power Pvt Ltd', '', NULL, 'O P Sahu', 'whatsapp', 'Rimpa', '2024-10-01 11:18:54+00', NULL),
  (NULL, 'Indent in Draft', 'They want to create indent in draft through through month and then final indent on 1st of every month', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2024-10-01 11:32:14+00', NOW(), NULL, 'Create Indent', NULL, 'Nutan Ispat & Power Pvt Ltd', 'Power', NULL, 'Nitesh Gupta', 'phone', 'Rimpa', '2024-10-01 11:32:14+00', NULL),
  (NULL, 'Indenter Name search in Pending PO (GRN)', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2024-10-21 10:24:06+00', NOW(), NULL, 'Pending Po (GRN)', NULL, 'Nutan Ispat & Power Pvt Ltd', 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', '2024-10-21 10:24:06+00', NULL),
  (NULL, 'Freight Cost to be included in item rate ?', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2024-10-21 10:32:44+00', NOW(), NULL, 'Pending Indent RFQ', NULL, 'Nutan Ispat & Power Pvt Ltd', 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', '2024-10-21 10:32:44+00', NULL),
  (NULL, 'Department column in GRN Register', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2024-10-21 10:45:51+00', NOW(), NULL, 'GRN Register', NULL, 'Nutan Ispat & Power Pvt Ltd', 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', '2024-10-21 10:45:51+00', NULL),
  (NULL, 'Item group in vendor selection (RFQ)- Multiple selection', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2024-10-21 10:51:56+00', NOW(), NULL, 'Pending Indent RFQ', NULL, 'Nutan Ispat & Power Pvt Ltd', 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', '2024-10-21 10:51:56+00', NULL),
  (NULL, 'Employee list (at time of Issue),Loan -No dues', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2024-10-21 10:53:33+00', NOW(), NULL, 'Issue', NULL, 'Nutan Ispat & Power Pvt Ltd', 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', '2024-10-21 10:53:33+00', NULL),
  (NULL, '1 item export - Issue & GRN to be allowed for 1year', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2024-10-21 10:57:46+00', NOW(), NULL, 'Issue Register', NULL, 'Nutan Ispat & Power Pvt Ltd', 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', '2024-10-21 10:57:46+00', NULL),
  (NULL, 'NRGP show brand wise stock', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2024-10-21 11:00:50+00', NOW(), NULL, 'Non returnable gate pass', NULL, 'Nutan Ispat & Power Pvt Ltd', 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', '2024-10-21 11:00:50+00', NULL),
  (NULL, 'Monthly budget Deducted for Indent Amount. Track that Amount for every Action, like PO Amount ,GRN Amount', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2024-10-21 11:03:57+00', NOW(), NULL, 'Monthly Budget', NULL, 'Nutan Ispat & Power Pvt Ltd', 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', '2024-10-21 11:03:57+00', NULL),
  (NULL, 'QC export - restrict edit access', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2024-10-21 11:33:06+00', NOW(), NULL, 'Pending Indent RFQ', NULL, 'Nutan Ispat & Power Pvt Ltd', 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', '2024-10-21 11:33:06+00', NULL),
  (NULL, 'Pending Indent - Delay from Approval days', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2024-10-21 11:35:13+00', NOW(), NULL, 'Indents to Approve', NULL, 'Nutan Ispat & Power Pvt Ltd', 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', '2024-10-21 11:35:13+00', NULL),
  (NULL, 'Should show QC status in PO approval & register', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2024-10-21 15:02:53+00', NOW(), NULL, 'PO Register', NULL, 'Nutan Ispat & Power Pvt Ltd', 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', '2024-10-21 15:02:53+00', NULL),
  (NULL, 'Update Quotation Comparison Page for WO', 'Quotation Comparison should be same in all functionality for WO as like PO.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2024-10-22 17:36:58+00', NOW(), NULL, 'Quotation Comparision', NULL, 'Demo_c', 'All', NULL, 'Shreyasi Mukherjee', 'phone', 'Shreyasi', '2024-10-22 17:36:58+00', NULL),
  (NULL, 'Other expenses like freight, etc have an option during preparation of GRN to add in GRN valuation', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2024-10-26 11:51:06+00', NOW(), NULL, 'GRN Register', NULL, 'Hariom Ingots & Power Pvt. Ltd.', 'CCM', NULL, 'Pradeep Kumar Satpati', 'whatsapp', 'Rimpa', '2024-10-26 11:51:06+00', NULL),
  (NULL, 'Multiple Approver Should be Reflect in GRN Slip', 'When Approvals will be in multiple level, in GRN Slip it should be showing as ''Approved By: Approver 1- <Name> Approver 2- <Name>''.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2024-11-12 13:14:27+00', NOW(), NULL, 'GRN Register', NULL, 'Demo_c', 'All', NULL, 'Shreyasi Mukherjee', 'phone', 'Shreyasi', '2024-11-12 13:14:27+00', NULL),
  (NULL, 'Update GRN approval process', 'Add two button in unapproved GRN slip. One is for GRN Date and another one is for Current Date approval.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-01-02 13:54:14+00', NOW(), NULL, 'GRN Approval', NULL, 'Odissa Concrete & Allied Industries Ltd', 'All', NULL, 'Praharsh Agarwal', 'whatsapp', 'Rimpa', '2025-01-02 13:54:14+00', NULL),
  (NULL, 'WhatsApp Notification for Item Approval', 'Once the item is approved, they would like to receive a notification indicating that the item has been approved so they can proceed with further action.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-01-04 12:58:11+00', NOW(), NULL, 'ITEM', NULL, 'Dadijee Steel Manufacturing & Trading Private Limited', 'All', NULL, 'Sudhir Kumar', 'whatsapp', 'Shreyasi', '2025-01-04 12:58:11+00', NULL),
  (NULL, 'Add Item Nature & Category details in Stock Summary and Stock Movement Report', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-01-08 09:33:54+00', NOW(), NULL, 'Stock Summary', NULL, 'Nutan Ispat & Power Pvt Ltd', 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', '2025-01-08 09:33:54+00', NULL),
  (NULL, 'Add partial payment option', 'In Payment sheet now we can pay the amount in total at a time but feature needs to be implemented, so that payment code be done in partial way as needed on different.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-01-14 15:14:45+00', NOW(), NULL, 'Payment Sheet', NULL, 'Demo_c', 'All', NULL, 'Rimpa Manik', 'phone', 'Rimpa', '2025-01-14 15:14:45+00', NULL),
  (NULL, 'If PO has been edited it should be track', 'If anyone edit the PO it should be track on trail under status column in PO Register', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-01-18 11:57:24+00', NOW(), NULL, 'PO Register', NULL, 'Demo_c', 'All', NULL, 'Rimpa Manik', 'phone', 'Rimpa', '2025-01-18 11:57:24+00', NULL),
  ('FE-0001', 'Feature in QC page of WO customised item picked QC export', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-01-23 11:27:40+00', NOW(), NULL, 'Quotation Comparison', NULL, 'Demo_c', 'All', NULL, 'Rimpa Manik', 'phone', 'Rimpa', '2025-01-23 11:27:40+00', NULL),
  ('FE-0002', 'Tag to Repair--> Return by', 'When tagging an item for repair, after selecting the return-by date and proceeding to the next step, the items are shown under Returnable Items as "Not Yet Received." However, the overdue date is not being displayed.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-01-23 14:57:55+00', NOW(), NULL, 'Items Pending to be sent for repair', NULL, 'Demo_c', 'All', NULL, 'Rimpa Manik', 'phone', 'Rimpa', '2025-01-23 14:57:55+00', NULL),
  ('FE-0005', 'Enable Print Option in WO & WRN Register.', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-02-17 17:18:29+00', NOW(), NULL, 'Dashboard', NULL, 'Spintech Tubes Pvt Ltd', 'All', NULL, 'STPL Central Stores', 'phone', 'Rimpa', '2025-02-17 17:18:29+00', NULL),
  ('FE-0006', 'Enable the Feature for Remark Note Box when Approving Indent and Add Column for Remark', 'Step 1: There should be an optional note box in Indent Approval. Step 2: A column should be shown in Indents to Approve and Pending Indent RFQ and Indent Register Page named as Remarks.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-02-26 10:42:42+00', NOW(), NULL, 'Indents to Approve', NULL, 'Nutan Ispat & Power Pvt Ltd', 'All', NULL, 'Dilip Das', 'whatsapp', 'Rimpa', '2025-02-26 10:42:42+00', NULL),
  ('FE-0009', 'Stock Summary--> Stock Movement Report add location column', 'Add a column for Location in the Stock Movement report', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-03-08 12:15:00+00', NOW(), NULL, 'Stock Summary', NULL, 'Nutan Ispat & Power Pvt Ltd', 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', '2025-03-08 12:15:00+00', NULL),
  ('FE-0013', 'Column customization should be enabled during the export of the payment sheet.', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-03-21 12:16:31+00', NOW(), NULL, 'Payment Sheet', NULL, 'Demo_c', 'All', NULL, 'Ayush Jhunjhunwala', 'phone', 'Rimpa', '2025-03-21 12:16:31+00', NULL),
  ('FE-0030', 'System should allow to Add Freight Cost Item wise when creating PO.', 'User Requirement is to add Freight Cost flexibly Item wise as per requirement.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-04-08 17:59:20+00', NOW(), NULL, 'Create Po', NULL, 'Agroha Steel and Power Pvt Ltd', 'All', NULL, 'Kamal Sahu', 'whatsapp', 'Aman', '2025-04-08 17:59:20+00', NULL),
  ('FE-0033', 'PO audit report export option should be customisable column', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-04-10 17:27:44+00', NOW(), NULL, 'PO Audit Report', NULL, 'Demo_c', 'All', NULL, 'Rimpa Manik', 'phone', 'Rimpa', '2025-04-10 17:27:44+00', NULL),
  ('FE-0037', 'Enable a filter option "Auto Short Close" in status filter under Pending Indent (RFQ) page', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-04-14 17:20:28+00', NOW(), NULL, 'Pending Indent RFQ', NULL, 'MVK Industries Pvt Ltd', 'All', NULL, 'Dinesh Bareth', 'phone', 'Rimpa', '2025-04-14 17:20:28+00', NULL),
  ('FE-0042', 'Add MSME no in PO slip', 'Add MSME no in PO slip same as GST no under Supplier details', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-04-26 14:16:12+00', NOW(), NULL, 'PO Register', NULL, 'Rashmi Sponge Iron & Power Industries Pvt. Limited', 'All', NULL, 'Gautam Kaushal', 'phone', 'Rimpa', '2025-04-26 14:16:12+00', NULL),
  ('FE-0047', 'Implement a customise report for QC', 'In this report user want to see the item wise enquires, quotes, rate given by vendors and date for each requirement they have faced.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-05-03 09:50:44+00', NOW(), NULL, 'Reports', NULL, 'Rausheena Udyog Limited', 'All', NULL, 'Abhranil Paul', 'whatsapp', 'Rimpa', '2025-05-03 09:50:44+00', NULL),
  ('FE-0048', 'Implement the feature for all companies of Maan group', 'Please arrange gross total in last page', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-05-03 10:02:05+00', NOW(), NULL, 'Pending for Tally Entry', NULL, 'Maanheruka', 'All', NULL, 'Satish Dokania', 'whatsapp', 'Rimpa', '2025-05-03 10:02:05+00', NULL),
  ('FE-0049', 'Implement the feature for all companies of Maan group', 'Please arrange gross total in last page', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-05-03 10:04:04+00', NOW(), NULL, 'Pending Bills', NULL, 'Maanheruka', 'All', NULL, 'Satish Dokania', 'whatsapp', 'Rimpa', '2025-05-03 10:04:04+00', NULL),
  ('FE-0050', 'Implement the feature for all companies of Maan group', 'Please arrange gross total in last page', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-05-03 10:05:18+00', NOW(), NULL, 'Payment Sheet', NULL, 'Maanheruka', 'All', NULL, 'Satish Dokania', 'whatsapp', 'Rimpa', '2025-05-03 10:05:18+00', NULL),
  ('FE-0053', 'IGST toggle should be on for outside vendors.', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-05-09 17:08:59+00', NOW(), NULL, 'Stock Summary', NULL, 'Sky Alloys and Power Limited', 'All', NULL, 'Dhirendra Patra', 'mail', 'Shreyasi', '2025-05-09 17:08:59+00', NULL),
  ('FE-0055', 'Date in order', 'There is should be a feature in this page by which in the filter section, i can select date of request made/ date of approved in ascending/ descending order. Currently, its in descending order. Also, not only in this page, but in all pages, this feature should be added', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-05-13 12:23:34+00', NOW(), NULL, 'Pending Indent RFQ', NULL, 'Demo_c', 'All', NULL, 'Shubham Kejriwal', 'phone', 'Aman', '2025-05-13 12:23:34+00', NULL),
  ('FE-0060', 'Quote By add in Quotation page', 'Add Quotation revised by user or vendor it reflect on the QC page.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-05-19 17:54:52+00', NOW(), NULL, 'Quotation Comparison', NULL, 'Balmukund Sponge Iron Pvt. Ltd.', 'All', NULL, 'Ankit Verma', 'phone', 'Rimpa', '2025-05-19 17:54:52+00', NULL),
  ('FE-0061', 'Add Negotiation rate in QC', 'Add negotiated percentage after negotiation just under Price bid history, basically in QC page reflect the negotiation percentage. Example: Initial rate Rs10, negotiated rate Rs5, we have to reflect just under the price bid history Negotiated 50%', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-05-19 18:00:32+00', NOW(), NULL, 'Quotation Comparison', NULL, 'Balmukund Sponge Iron Pvt. Ltd.', 'All', NULL, 'Ankit Verma', 'phone', 'Rimpa', '2025-05-19 18:00:32+00', NULL),
  ('FE-0064', 'Add Price bid history in WO RFQ QC page', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-06-02 12:15:18+00', NOW(), NULL, 'Quotation Comparison', NULL, 'Demo_c', 'All', NULL, 'Rimpa Manik', 'phone', 'Shreyasi', '2025-06-02 12:15:18+00', NULL),
  ('FE-0065', 'A new field named TYPE will be added to the Add New Item page', 'Dropdown with options: RM, Store & Spare, and Consumable.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-06-06 17:07:10+00', NOW(), NULL, 'ITEM', NULL, 'Balmukund Sponge Iron Pvt. Ltd.', 'All', NULL, 'Ankit Verma', 'whatsapp', 'Aman', '2025-06-06 17:07:10+00', NULL),
  ('FE-0067', 'Add an Unapprove Button', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-06-09 13:09:51+00', NOW(), NULL, 'GRNs to Approve', NULL, 'Demo_c', 'All', NULL, 'Shreyasi Mukherjee', 'phone', 'Shreyasi', '2025-06-09 13:09:51+00', NULL),
  ('FE-0070', 'Add an Unapprove Button', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-06-09 13:13:08+00', NOW(), NULL, 'Stock Adjustment Approvals', NULL, 'Demo_c', 'All', NULL, 'Shreyasi Mukherjee', 'phone', 'Shreyasi', '2025-06-09 13:13:08+00', NULL),
  ('FE-0071', 'Add an Unapprove Button', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-06-09 13:14:30+00', NOW(), NULL, 'Physical Stocks to Approve', NULL, 'Demo_c', 'All', NULL, 'Shreyasi Mukherjee', 'phone', 'Shreyasi', '2025-06-09 13:14:30+00', NULL),
  ('FE-0072', 'WO Indents Approvals should reflect over Dashboard', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-06-09 16:16:22+00', NOW(), NULL, 'Dashboard', NULL, 'MVK Industries Pvt Ltd', 'All', NULL, 'Dinesh Bareth', 'whatsapp', 'Shreyasi', '2025-06-09 16:16:22+00', NULL),
  ('FE-0076', 'We should track items shelf life', 'When an user input an item shelf life in GRN Entry page it should be tracked in system. Also there should be a functionality to take further action when the warranty period get exceed.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-06-18 16:24:57+00', NOW(), NULL, 'GRN Entry', NULL, 'Demo_c', 'All', NULL, 'Rimpa Manik', 'phone', 'Shreyasi', '2025-06-18 16:24:57+00', NULL),
  ('FE-0078', 'Track the all deleted details like Indent, PO, GRN, Issue', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-07-04 17:18:45+00', NOW(), NULL, 'Reports', NULL, 'Demo_c', 'All', NULL, 'Shreyasi Mukherjee', 'phone', 'Shreyasi', '2025-07-04 17:18:45+00', NULL),
  ('FE-0080', 'Add a feature for Gate entry without PO', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-07-14 17:36:52+00', NOW(), NULL, 'Dashboard', NULL, 'Brahmaputra Metallics Ltd.', 'All', NULL, 'Mrityunjoy Debnath', 'whatsapp', 'Rimpa', '2025-07-14 17:36:52+00', NULL),
  ('FE-0081', 'The purchaser wants to use a notification for the Clarify option under Pending Indent RFQ', 'When Clarify button is clicked, a notification should go to the indent raiser. Notification should send in mail or whatsapp', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-08-02 13:23:21+00', NOW(), NULL, 'Pending Indent RFQ', NULL, 'Roopgarh Power & Alloys Pvt. Ltd', 'All', NULL, 'Divyesh Singhaniya', 'phone', 'Rimpa', '2025-08-02 13:23:21+00', NULL),
  ('FE-0082', 'The user wants to add multiple items in Issue Tools on a returnable basis, same like issue', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-08-12 12:25:10+00', NOW(), NULL, 'Issue Tools on Returnable Basis', NULL, 'Sky Alloys and Power Limited', 'All', NULL, 'Manoj Kumar Mohanty', 'phone', 'Rimpa', '2025-08-12 12:25:10+00', NULL),
  ('FE-0083', 'Enable Approval option for Tag vendor', 'If a user tags a vendor with a brand, item, and item group, an approval process should be enabled after the vendor tagging.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-08-14 13:17:57+00', NOW(), NULL, 'Approvals', NULL, 'Demo_c', 'All', NULL, 'Ayush Jhunjhunwala', 'whatsapp', 'Rimpa', '2025-08-14 13:17:57+00', NULL),
  ('FE-0084', 'The user wants to see, during QC, how many relevant vendors have not received the enquiry from us', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-08-25 17:20:14+00', NOW(), NULL, 'Pending Indent RFQ', NULL, 'Hi-Tech Power & Steel Ltd.', 'All', NULL, 'Kamal Agrawal', 'phone', 'Rimpa', '2025-08-25 17:20:14+00', NULL),
  ('FE-0085', 'Test Feature', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-09-11 16:41:45+00', NOW(), NULL, 'Create Indent', NULL, 'Demo_c', 'All', NULL, 'Rimpa', 'phone', 'Rimpa', '2025-09-11 16:41:45+00', NULL),
  ('FE-0096', 'Make master id for approval', 'For now just implement the system with any id one of us. Where from a single id approval could be given at any level.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-11-12 09:41:46+00', NOW(), NULL, 'Users', NULL, 'Hi-Tech Power & Steel Ltd.', 'All', NULL, 'Pallav Tiwari', 'phone', 'Shreyasi', '2025-11-12 09:41:46+00', NULL),
  ('FE-0097', 'Build mobile application', 'Build mobile application with the most important things - dashboard, approvals, Pending Indent and GRN, item stock, notifications.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-12-04 11:48:49+00', NOW(), NULL, 'Dashboard', NULL, 'BIHAR FOUNDRY', 'All', NULL, 'Somnath Roy', 'mail', 'Shreyasi', '2025-12-04 11:48:49+00', NULL),
  ('FE-0098', 'Generate all Reports for Services also', 'As we are maintaining the Inventory and Purchases for products, user want to manage the inventory through our software for Services (Work Orders).', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-12-04 13:00:51+00', NOW(), NULL, 'Reports', NULL, 'BIHAR FOUNDRY', 'All', NULL, 'Somnath Roy', 'mail', 'Shreyasi', '2025-12-04 13:00:51+00', NULL),
  ('FE-0099', 'We need an Indent Approval in email, similar to the one used for PO.', 'Format will be same like PO approval format via mail. Mandatory: Indent Number, Approve and Un-Approve button', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-12-08 13:55:36+00', NOW(), NULL, 'Indents to Approve', NULL, 'Flexicom Industries Pvt. Ltd.', 'All', NULL, 'pallab salampuria', 'whatsapp', 'Shreyasi', '2025-12-08 13:55:36+00', NULL),
  ('FE-0100', 'Enable all approval processes through WhatsApp.', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-12-08 14:55:03+00', NOW(), NULL, 'Approvals', NULL, 'Demo_c', 'All', NULL, 'Ayush Jhunjhunwala', 'whatsapp', 'Shreyasi', '2025-12-08 14:55:03+00', NULL),
  ('FE-0101', 'Enable Draft in Indent.', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-12-08 16:19:04+00', NOW(), NULL, 'Create Indent', NULL, 'BIHAR FOUNDRY', 'All', NULL, 'Somnath', 'phone', 'Shreyasi', '2025-12-08 16:19:04+00', NULL),
  ('FE-0103', 'Mentioned the edited element (exactly which field has been edited)', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-12-09 17:48:14+00', NOW(), NULL, 'Indent Register', NULL, 'BIHAR FOUNDRY', 'All', NULL, 'Somnath Roy', 'mail', 'Shreyasi', '2025-12-09 17:48:14+00', NULL),
  ('FE-0104', 'Add information in status trail', 'Add informations for if any user or approver edit anything. Mentioned Edited by. Exactly which field has been edited', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-12-09 17:50:10+00', NOW(), NULL, 'Work Order Indent Register', NULL, 'BIHAR FOUNDRY', 'All', NULL, 'Somnath Roy', 'mail', 'Shreyasi', '2025-12-09 17:50:10+00', NULL),
  ('FE-0105', 'Add information in status trail', 'Add informations for if any user or approver edit anything. Mentioned Edited by. Exactly which field has been edited', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-12-09 17:52:20+00', NOW(), NULL, 'PO Register', NULL, 'BIHAR FOUNDRY', 'All', NULL, 'Somnath Roy', 'mail', 'Shreyasi', '2025-12-09 17:52:20+00', NULL),
  ('FE-0106', 'Add information in status trail', 'Add informations for if any user or approver edit anything. Mentioned Edited by. Exactly which field has been edited', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-12-09 17:56:02+00', NOW(), NULL, 'Work Order Register', NULL, 'BIHAR FOUNDRY', 'All', NULL, 'Somnath Roy', 'mail', 'Shreyasi', '2025-12-09 17:56:02+00', NULL),
  ('FE-0107', 'Add information in status trail', 'Add informations for if any user or approver edit anything. Mentioned Edited by. Exactly which field has been edited', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-12-10 09:39:08+00', NOW(), NULL, 'Vendors', NULL, 'BIHAR FOUNDRY', 'All', NULL, 'Somnath Roy', 'mail', 'Shreyasi', '2025-12-10 09:39:08+00', NULL),
  ('FE-0108', 'Add information in status trail', 'Add informations for if any user or approver edit anything. (GRN approval Transactions & Notifications) Mentioned Edited by. Exactly which field has been edited', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-12-10 09:41:55+00', NOW(), NULL, 'GRN Register', NULL, 'BIHAR FOUNDRY', 'All', NULL, 'Somnath Roy', 'mail', 'Shreyasi', '2025-12-10 09:41:55+00', NULL),
  ('FE-0109', 'Add information in status trail', 'Add informations for if any user or approver edit anything. Mentioned Edited by. Exactly which field has been edited', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-12-10 09:44:09+00', NOW(), NULL, 'WRN Register', NULL, 'BIHAR FOUNDRY', 'All', NULL, 'Somnath Roy', 'mail', 'Shreyasi', '2025-12-10 09:44:09+00', NULL),
  ('FE-0110', 'Add information in status trail', 'Add informations for if any user or approver edit anything. Mentioned Edited by. Exactly which field has been edited', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-12-10 09:46:13+00', NOW(), NULL, 'Issue Register', NULL, 'BIHAR FOUNDRY', 'All', NULL, 'Somnath Roy', 'mail', 'Shreyasi', '2025-12-10 09:46:13+00', NULL),
  ('FE-0111', 'Add information in status trail', 'Add informations for if any user or approver edit anything. Mentioned Edited by. Exactly which field has been edited', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-12-10 09:48:13+00', NOW(), NULL, 'Stock Adjustment Register', NULL, 'BIHAR FOUNDRY', 'All', NULL, 'Somnath Roy', 'mail', 'Shreyasi', '2025-12-10 09:48:13+00', NULL),
  ('FE-0112', 'Create Production--> User-->Pull from Indenter', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-12-10 14:32:39+00', NOW(), NULL, 'EMS Dashboard', NULL, 'Demo_c', 'All', NULL, 'Rimpa', 'phone', 'Rimpa', '2025-12-10 14:32:39+00', NULL),
  ('FE-0113', 'Add feature (Level filter option)', 'Notification>POs to approve page, add level filter option for better search.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-12-23 17:51:11+00', NOW(), NULL, 'POs To Approve', NULL, 'BIHAR FOUNDRY', 'All', NULL, 'Abhas', 'whatsapp', 'Subhomoy', '2025-12-23 17:51:11+00', NULL),
  ('FE-0114', 'Add department filter as new feature', 'Asked a department-wise filter in POs to Approve sections.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-12-26 13:33:01+00', NOW(), NULL, 'POs To Approve', NULL, 'BIHAR FOUNDRY', 'All', NULL, 'Somnath Roy', 'whatsapp', 'Subhomoy', '2025-12-26 13:33:01+00', NULL),
  ('FE-0115', 'Add department filter as new feature', 'Asked a department-wise filter in PO Register sections.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-12-26 13:36:46+00', NOW(), NULL, 'PO Register', NULL, 'BIHAR FOUNDRY', 'All', NULL, 'Somnath Roy', 'whatsapp', 'Subhomoy', '2025-12-26 13:36:46+00', NULL),
  ('FE-0116', 'PO related notification to be enabled', 'PO related notification to be sent in WhatsApp with complete PO details.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-12-26 15:25:47+00', NOW(), NULL, 'Whatsapp IndustryPrime', NULL, 'BIHAR FOUNDRY', 'All', NULL, 'Somnath Roy', 'whatsapp', 'Subhomoy', '2025-12-26 15:25:47+00', NULL),
  ('FE-0117', 'Add checkbox feature beside divisions', 'New Feature of checkboxes next to divisions, allowing them to select multiple divisions and view combined data for only the selected divisions on the dashboard.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-12-26 15:32:11+00', NOW(), NULL, 'Dashboard', NULL, 'BIHAR FOUNDRY', 'All', NULL, 'Somnath Roy', 'whatsapp', 'Subhomoy', '2025-12-26 15:32:11+00', NULL),
  ('FE-0118', 'Notifications to be sent (Division - Department Wise)', 'As there are many departments under divisions, one who have access to a particular department should get notifications related to that specified departments only.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2025-12-26 15:41:34+00', NOW(), NULL, 'Notifications', NULL, 'BIHAR FOUNDRY', 'All', NULL, 'Somnath Roy', 'whatsapp', 'Subhomoy', '2025-12-26 15:41:34+00', NULL),
  ('FE-0119', 'Notification feature needed for Sales Order', 'After creating a sales order user wants a WhatsApp notification like, Sales order arrive <Sales Order Number>', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2026-01-15 17:30:40+00', NOW(), NULL, 'EMS Dashboard', NULL, 'KSK Engineering Industries Pvt Ltd', 'All', NULL, 'Manish Kumar', 'whatsapp', 'Shreyasi', '2026-01-15 17:30:40+00', NULL),
  ('FE-0120', 'Calculate the difference in between the vendor invoice and actual GRN', 'Calculate each and every difference between the vendor invoice and actual GRN. This difference should be reflected in GRN slip and GRN register.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2026-01-29 14:21:47+00', NOW(), NULL, 'GRN Entry', NULL, 'Bhagwati Power Pvt. Ltd.', 'All', NULL, 'Vishawnath', 'phone', 'Rimpa', '2026-01-29 14:21:47+00', NULL),
  ('FE-0121', 'User wants auto item creation and bulk enquiry upload', 'Same feature which enabled for crescent - when system pull the enquiry or bulk upload, check if item present in software or not, if not then auto create the item.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2026-01-30 17:50:41+00', NOW(), NULL, 'EMS Dashboard', NULL, 'KSK Engineering Industries Pvt Ltd', 'All', NULL, 'Prateek', 'whatsapp', 'Shreyasi', '2026-01-30 17:50:41+00', NULL),
  ('FE-0123', 'Add Production in Enquiry central', 'Link ENQUIRIES--> QUOTATIONS--> ORDERS--> PRODUCTION--> DISPATCH', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2026-02-09 12:08:21+00', NOW(), NULL, 'EMS Dashboard', NULL, 'Odissa Concrete & Allied Industries Ltd', 'All', NULL, 'P Suresh', 'phone', 'Rimpa', '2026-02-09 12:08:21+00', NULL),
  ('FE-0125', 'NR Required to Add for item Stock', 'Add an option in the Stock Ledger under the Detailed View of Item Stock. Users should be able to mark stocks as NR. The Stock Ledger should track NR-marked stock. NR-marked stock should not be available for any transactions.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2026-02-10 11:08:44+00', NOW(), NULL, 'ITEM', NULL, 'Sky Alloys and Power Limited', 'All', NULL, 'Dhiren Patra', 'whatsapp', 'Rimpa', '2026-02-10 11:08:44+00', NULL),
  ('FE-0127', 'User want tolerance in GRN basis of valuation of the PO instead of UOM', '', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2026-02-12 17:53:22+00', NOW(), NULL, 'GRN Entry', NULL, 'Bhagwati Power Pvt. Ltd.', 'All', NULL, 'Kashyap Kejriwal', 'phone', 'Rimpa', '2026-02-12 17:53:22+00', NULL),
  ('FE-0128', 'Add tolerance in create PO page and by default tolerance will be blank or 0', 'Add a option to add tolerance in PO creation time. Add a checkbox for tolerance in PO by default tolerance will be blank or 0 and if user click the checkbox then put tolerance %.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2026-02-16 16:53:46+00', NOW(), NULL, 'Create Po', NULL, 'Bhagwati Power Pvt. Ltd.', 'All', NULL, 'Kashyap Kejriwal', 'phone', 'Rimpa', '2026-02-16 16:53:46+00', NULL),
  (NULL, 'User wants to create Material Identification Tag after GRN creation', 'From GRN register user wants to generate a Material Identification Tag show that they can track and print that tag for each material. As you discussed, generating material identification tags in software will provide several benefits, such as adding material codes to material issues.', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2026-02-24 17:21:00+00', NOW(), NULL, 'GRN Register', NULL, 'Nirmaan TMT', 'All', NULL, 'Domen Dewangan', 'phone', 'Rimpa Manik', '2026-02-24 17:21:00+00', NULL),
  (NULL, 'Cancellation mail required for PO', 'When PO is cancelled, a PO cancelled mail should be sent to the vendor automatically (just like it happens during PO Creation)', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2026-02-25 14:34:00+00', NOW(), NULL, NULL, NULL, 'Sky Alloys and Power Pvt Ltd', 'All', NULL, 'Arjun Malakar', 'phone', 'Rimpa Manik', '2026-02-25 14:34:00+00', NULL),
  (NULL, 'Implement Debit note', 'User wants a debit note implementation. We have to implement debit note in 2 places. 1. Enable a option in three dot named like "Create Debit note" or "print debit note" under purchase return register. 2. Also allow the same whenever user marks an GRN as purchase return from GRN register a Pop up should arrived in user interface name like "Do you want to create debit note?"', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), '2026-03-07 12:00:00+00', NOW(), NULL, 'Dashboard', NULL, 'Hi-Tech', 'All', NULL, 'Vishwanath', 'phone', 'Rimpa Manik', '2026-03-07 12:00:00+00', NULL)
ON CONFLICT (reference_no) DO NOTHING;
