-- ============================================================================
-- Feature tickets INSERT – visible in "Approval Status" (Support dropdown)
-- ============================================================================
-- Run TICKETS_ADD_SUPPORT_COLUMNS.sql first if column "page" does not exist.
-- Requires: public.companies, public.pages, public.user_profiles have at least one row.
--
-- Why feature tickets did not show:
-- - App shows feature tickets in "Approval Status" only when approval_status IS NULL or 'unapproved'.
-- - "Completed Feature" shows only approval_status = 'approved'.
-- - This script sets approval_status = NULL so they appear under Approval Status.
-- - ON CONFLICT updates existing rows so they become visible again if already in DB.
-- ============================================================================

INSERT INTO public.tickets (
  reference_no, title, description, type, status, priority,
  company_id, division_id, created_by, created_at, updated_at,
  attachment_url, page, page_id, company_name, division, division_other, user_name,
  communicated_through, submitted_by, query_arrival_at, quality_of_response,
  customer_questions, query_response_at,
  approval_status
) VALUES
  ('FE-0129', 'Issue posting karte samay rate or amount dikhana chahiye', 'Issue posting karte samay rate or amount dikhana chahiye Old Ref: - Time Delay: 504 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), 'https://drive.google.com/open?id=1N1U21AWPfIVmsllZSknnVp4l-F_CcOo0', 'Issue', (SELECT id FROM public.pages WHERE name = 'Issue' LIMIT 1), NULL, 'All', NULL, 'O P Sahu', 'whatsapp', 'Rimpa', NOW() - interval '504 days', NULL, NULL, NULL, NULL),
  ('FE-0130', 'Indent in Draft', 'They want to create indent in draft through through month and then final indent on 1st of every month Old Ref: - Time Delay: 504 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), NULL, 'Create Indent', (SELECT id FROM public.pages WHERE name = 'Create Indent' LIMIT 1), NULL, 'Power', NULL, 'Nitesh Gupta', 'phone', 'Rimpa', NOW() - interval '504 days', NULL, NULL, NULL, NULL),
  ('FE-0131', 'Indenter Name search in Pending PO (GRN)', 'Indenter Name search in Pending PO (GRN) Old Ref: - Time Delay: 484 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), NULL, 'Pending PO (GRN)', (SELECT id FROM public.pages WHERE name = 'Pending PO (GRN)' LIMIT 1), NULL, 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', NOW() - interval '484 days', NULL, NULL, NULL, NULL),
  ('FE-0132', 'Freight Cost to be included in item rate ?', 'Freight Cost to be included in item rate ? Old Ref: - Time Delay: 484 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), NULL, 'Pending Indent RFQ', (SELECT id FROM public.pages WHERE name = 'Pending Indent RFQ' LIMIT 1), NULL, 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', NOW() - interval '484 days', NULL, NULL, NULL, NULL),
  ('FE-0133', 'Department column in GRN Register', 'Department column in GRN Register Old Ref: - Time Delay: 484 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), NULL, 'GRN Register', (SELECT id FROM public.pages WHERE name = 'GRN Register' LIMIT 1), NULL, 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', NOW() - interval '484 days', NULL, NULL, NULL, NULL),
  ('FE-0134', 'Item group in vendor selection (RFQ)- Multiple selection', 'Item group in vendor selection (RFQ)- Multiple selection Old Ref: - Time Delay: 484 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), NULL, 'Pending Indent RFQ', (SELECT id FROM public.pages WHERE name = 'Pending Indent RFQ' LIMIT 1), NULL, 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', NOW() - interval '484 days', NULL, NULL, NULL, NULL),
  ('FE-0135', 'Employee list (at time of Issue),Loan -No dues', 'Employee list (at time of Issue),Loan -No dues Old Ref: - Time Delay: 484 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), NULL, 'Issue', (SELECT id FROM public.pages WHERE name = 'Issue' LIMIT 1), NULL, 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', NOW() - interval '484 days', NULL, NULL, NULL, NULL),
  ('FE-0136', '1 item export - Issue & GRN to be allowed for 1year', '1 item export - Issue & GRN to be allowed for 1year Old Ref: - Time Delay: 484 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), NULL, 'Issue Register', (SELECT id FROM public.pages WHERE name = 'Issue Register' LIMIT 1), NULL, 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', NOW() - interval '484 days', NULL, NULL, NULL, NULL),
  ('FE-0137', 'NRGP show brand wise stock', 'NRGP show brand wise stock Old Ref: - Time Delay: 484 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), NULL, 'Non-returnable Gate Pass', (SELECT id FROM public.pages WHERE name = 'Non-returnable Gate Pass' LIMIT 1), NULL, 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', NOW() - interval '484 days', NULL, NULL, NULL, NULL),
  ('FE-0138', 'Monthly budget Deducted for Indent Amount. Track that Amount for every Action, like PO Amount ,GRN Amount', 'Monthly budget Deducted for Indent Amount. Track that Amount for every Action, like PO Amount ,GRN Amount Old Ref: - Time Delay: 484 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), NULL, 'Monthly Budget', (SELECT id FROM public.pages WHERE name = 'Monthly Budget' LIMIT 1), NULL, 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', NOW() - interval '484 days', NULL, NULL, NULL, NULL),
  ('FE-0139', 'QC export - restrict edit access', 'QC export - restrict edit access Old Ref: - Time Delay: 484 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), NULL, 'Pending Indent RFQ', (SELECT id FROM public.pages WHERE name = 'Pending Indent RFQ' LIMIT 1), NULL, 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', NOW() - interval '484 days', NULL, NULL, NULL, NULL),
  ('FE-0140', 'Pending Indent - Delay from Approval days', 'Pending Indent - Delay from Approval days Old Ref: - Time Delay: 484 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), NULL, 'Indents to Approve', (SELECT id FROM public.pages WHERE name = 'Indents to Approve' LIMIT 1), NULL, 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', NOW() - interval '484 days', NULL, NULL, NULL, NULL),
  ('FE-0141', 'Should show QC status in PO approval & register', 'Should show QC status in PO approval & register Old Ref: - Time Delay: 484 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), NULL, 'PO Register', (SELECT id FROM public.pages WHERE name = 'PO Register' LIMIT 1), NULL, 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', NOW() - interval '484 days', NULL, NULL, NULL, NULL),
  ('FE-0142', 'Update Quotation Comparison Page for WO', 'Quotation Comparison should be same in all functionality for WO as like PO. Old Ref: - Time Delay: 483 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), NULL, 'Quotation Comparison', (SELECT id FROM public.pages WHERE name = 'Quotation Comparison' LIMIT 1), NULL, 'All', NULL, 'Shreyasi Mukherjee', 'phone', 'Shreyasi', NOW() - interval '483 days', NULL, NULL, NULL, NULL),
  ('FE-0143', 'Other expenses like freight, etc have an option  during preparation of GRN to add in GRN valuation', 'Other expenses like freight, etc have an option  during preparation of GRN to add in GRN valuation Old Ref: - Time Delay: 479 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), NULL, 'GRN Register', (SELECT id FROM public.pages WHERE name = 'GRN Register' LIMIT 1), NULL, 'CCM', NULL, 'Pradeep Kumar Satpati', 'whatsapp', 'Rimpa', NOW() - interval '479 days', NULL, NULL, NULL, NULL),
  ('FE-0144', 'Multiple Approver Should be Reflect in GRN Slip', '"When Approvals  will be in multiple level, in GRN Slip it should be showing as ''''Approved By: Approver 1- <Name>       Approver 2- <Name>''''." Old Ref: - Time Delay: 462 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), NULL, 'GRN Register', (SELECT id FROM public.pages WHERE name = 'GRN Register' LIMIT 1), NULL, 'All', NULL, 'Shreyasi Mukherjee', 'phone', 'Shreyasi', NOW() - interval '462 days', NULL, NULL, NULL, NULL),
  ('FE-0145', 'Update GRN approval process', 'Add two button in unapproved GRN slip. One is for GRN Date and another one is for Current Date approval. Old Ref: - Time Delay: 411 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), NULL, 'GRN Approval', (SELECT id FROM public.pages WHERE name = 'GRN Approval' LIMIT 1), NULL, 'All', NULL, 'Praharsh Agarwal', 'whatsapp', 'Rimpa', NOW() - interval '411 days', NULL, NULL, NULL, NULL),
  ('FE-0146', 'WhatsApp Notification for Item Approval', 'Once the item is approved, they would like to receive a notification indicating that the item has been approved so they can proceed with further action. Old Ref: - Time Delay: 409 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), NULL, 'ITEM', (SELECT id FROM public.pages WHERE name = 'ITEM' LIMIT 1), NULL, 'All', NULL, 'Sudhir Kumar', 'whatsapp', 'Shreyasi', NOW() - interval '409 days', NULL, NULL, NULL, NULL),
  ('FE-0147', 'Add Item Nature & Category details in Stock Summary and Stock Movement Report', 'Add Item Nature & Category details in Stock Summary and Stock Movement Report Old Ref: - Time Delay: 405 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), NULL, 'Stock Summary', (SELECT id FROM public.pages WHERE name = 'Stock Summary' LIMIT 1), NULL, 'All', NULL, 'O P Sahu', 'phone', 'Rimpa', NOW() - interval '405 days', NULL, NULL, NULL, NULL),
  ('FE-0148', 'Add partial payment option', 'In Payment sheet now we can pay the amount in total at a time but feature needs to be implemented , so that payment code be done in partial way as needed on different. Old Ref: - Time Delay: 399 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), NULL, 'Payment Sheet', (SELECT id FROM public.pages WHERE name = 'Payment Sheet' LIMIT 1), NULL, 'All', NULL, 'Rimpa Manik', 'phone', 'Rimpa', NOW() - interval '399 days', NULL, NULL, NULL, NULL),
  ('FE-0149', 'If PO has been edited it should be track', 'If anyone edit the PO it should be track on trail under status column in PO Register Old Ref: - Time Delay: 395 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), NULL, 'PO Register', (SELECT id FROM public.pages WHERE name = 'PO Register' LIMIT 1), NULL, 'All', NULL, 'Rimpa Manik', 'phone', 'Rimpa', NOW() - interval '395 days', NULL, NULL, NULL, NULL),
  ('FE-0150', 'Feature in QC page of WO customised item picked QC export', 'Feature in QC page of WO customised item picked QC export Old Ref: FE-0001 Time Delay: 390 days', 'feature', 'open', 'medium', (SELECT id FROM public.companies LIMIT 1), NULL, (SELECT id FROM public.user_profiles LIMIT 1), NOW(), NOW(), NULL, 'Quotation Comparison', (SELECT id FROM public.pages WHERE name = 'Quotation Comparison' LIMIT 1), NULL, 'All', NULL, 'Rimpa Manik', 'phone', 'Rimpa', NOW() - interval '390 days', NULL, NULL, NULL, NULL)
ON CONFLICT (reference_no) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  type = EXCLUDED.type,
  status = EXCLUDED.status,
  updated_at = EXCLUDED.updated_at,
  attachment_url = EXCLUDED.attachment_url,
  page = EXCLUDED.page,
  page_id = EXCLUDED.page_id,
  company_name = EXCLUDED.company_name,
  division = EXCLUDED.division,
  division_other = EXCLUDED.division_other,
  user_name = EXCLUDED.user_name,
  communicated_through = EXCLUDED.communicated_through,
  submitted_by = EXCLUDED.submitted_by,
  query_arrival_at = EXCLUDED.query_arrival_at,
  quality_of_response = EXCLUDED.quality_of_response,
  customer_questions = EXCLUDED.customer_questions,
  query_response_at = EXCLUDED.query_response_at,
  approval_status = NULL;
