#!/usr/bin/env python3
"""
Generate SQL to import leads from the Client-to-Lead sheet (TSV).
- Reference number: auto-generated as IMP0001, IMP0002, ...
- created_at: from Lead Generation Date (DD/MM/YYYY) when present
- Status: Open / Closed -> leads.status
- Stage: sheet Stage -> leads.stage
- Assigned POC: resolved from user_profiles.full_name

Usage:
  python gen_lead_import_sql.py < leads_sheet.tsv > IMPORT_LEADS_FROM_SHEET.sql
  Or: python gen_lead_import_sql.py leads_sheet.tsv
"""
import sys
import re

def escape_sql(s):
    if s is None or (isinstance(s, str) and not s.strip()):
        return "NULL"
    t = str(s).replace("\\", "\\\\").replace("'", "''").strip().replace("\n", " ").replace("\r", " ")
    if not t:
        return "NULL"
    return "'" + t + "'"

def to_iso_date(ddmmyyyy):
    """Convert DD/MM/YYYY or D/M/YYYY to YYYY-MM-DD for JSONB."""
    if not ddmmyyyy or not str(ddmmyyyy).strip():
        return None
    s = str(ddmmyyyy).strip()
    m = re.match(r"(\d{1,2})[/-](\d{1,2})[/-](\d{4})", s)
    if m:
        d, mo, y = m.group(1), m.group(2), m.group(3)
        return f"{y}-{mo.zfill(2)}-{d.zfill(2)}"
    return None

def col(row, idx):
    if idx is None or idx < 0 or idx >= len(row):
        return ""
    return (row[idx] or "").strip()

def main():
    if len(sys.argv) > 1:
        with open(sys.argv[1], encoding="utf-8", errors="replace") as f:
            lines = f.read().splitlines()
    else:
        lines = sys.stdin.read().splitlines()

    # Skip first line (stage names); second line = header
    if len(lines) < 2:
        print("-- No header/data found", file=sys.stderr)
        sys.exit(1)
    header_line = lines[1]
    headers = [h.strip() for h in header_line.split("\t")]
    # Map header name -> index
    hi = {}
    for i, h in enumerate(headers):
        hi[h] = i

    # Column indices (use exact header names from sheet)
    def idx(name):
        return hi.get(name, -1)

    data_rows = []
    for line in lines[2:]:
        if not line.strip():
            continue
        parts = line.split("\t")
        if len(parts) < 4:
            continue
        company = col(parts, idx("Company Name"))
        if not company:
            continue
        data_rows.append(parts)

    # Output SQL
    print("-- ============================================================================")
    print("-- Import leads from sheet into public.leads + public.lead_stage_data")
    print("-- Run in Supabase SQL Editor. Requires public.user_profiles (full_name).")
    print("-- Reference: IMP0001, IMP0002, ... ; created_at from Lead Generation Date.")
    print("-- ============================================================================")
    print("")
    print("CREATE SEQUENCE IF NOT EXISTS lead_import_ref_seq START 1;\n")
    print("DO $$")
    print("DECLARE")
    print("  r RECORD;")
    print("  lid UUID;")
    print("  ref_no TEXT;")
    print("  lead_gen_ts TIMESTAMPTZ;")
    print("  poc_id UUID;")
    print("BEGIN")
    for row in data_rows:
        company_name = col(row, idx("Company Name"))
        status = col(row, idx("Status")) or "Open"
        if status not in ("Open", "Closed"):
            status = "Open"
        stage = col(row, idx("Stage")) or "Lead"
        assigned_poc = col(row, idx("Assigned POC")) or ""
        person_name = col(row, idx("Person Name"))
        mobile_number = col(row, idx("Mobile Number"))
        email_id = col(row, idx("Email ID"))
        lead_gen_date = col(row, idx("Lead Generation Date"))
        lead_generated_by = col(row, idx("Lead Generated By"))
        contacted_date = col(row, idx("Contacted Date"))
        relevant = col(row, idx("Relevant?"))
        city = col(row, idx("City"))
        state = col(row, idx("State"))
        industry = col(row, idx("Industry"))
        no_of_divisions = col(row, idx("No of Divisions"))
        name_of_divisions = col(row, idx("Name of Divisions"))
        designation = col(row, idx("Designation of Person"))
        company_desc = col(row, idx("Company Description"))
        inventory_type = col(row, idx("Inventory Type Management Needed for?"))
        brochure_sent = col(row, idx("Brochure Sent?"))
        brochure_sent_date = col(row, idx("Brochure Sent Date"))
        demo_finalized = col(row, idx("Date On which Demo Schedule was finalized?"))
        demo_scheduled_date = col(row, idx("Demo Scheduled Date"))
        demo_time = col(row, idx("Demo Time"))
        people_attending = col(row, idx("People Attending"))
        roles_attendees = col(row, idx("Roles of Attendees"))
        attendees_emails = col(row, idx("Attendees Emails"))
        attendees_mobile = col(row, idx("Attendees Mobile No"))
        demo_status = col(row, idx("Demo Status"))
        demo_date = col(row, idx("Demo Date"))
        demo_conducted_by = col(row, idx("Demo Conducted By"))
        attendee_names = col(row, idx("Attendee Names"))
        video_recorded = col(row, idx("Video Recorded"))
        video_uploaded = col(row, idx("Video Uploaded"))
        demo_duration = col(row, idx("Demo Duration"))
        interest_shown = col(row, idx("Interest Shown"))
        offer_letter_sent = col(row, idx("Offer Letter Sent?"))
        offer_letter_sent_date = col(row, idx("Offer Letter Sent Date"))
        offer_letter_approved = col(row, idx("Offer Letter Approved?"))
        offer_letter_approved_date = col(row, idx("Offer Letter Approved Date"))
        po_format_sent = col(row, idx("PO Format Sent?"))
        po_format_sent_date = col(row, idx("PO Format Sent Date"))
        po_received = col(row, idx("PO Recieved?")) or col(row, idx("PO Received?"))
        po_received_date = col(row, idx("PO Received Date"))
        performa_sent = col(row, idx("Performa Invoice Sent?"))
        performa_sent_date = col(row, idx("Performa Invoice Sent Date"))
        payment_received = col(row, idx("Payment Received?"))
        payment_received_date = col(row, idx("Payment Received Date.")) or col(row, idx("Payment Received Date"))
        impl_sent = col(row, idx("Implementation Invoice Sent?"))
        impl_date_sent = col(row, idx("Date Sent"))
        whatsapp_created = col(row, idx("WhatsApp Group Created"))
        whatsapp_date = col(row, idx("Date Created on?"))
        setup_sent = col(row, idx("Setup Details Sent?"))
        setup_sent_date = col(row, idx("Sent Date"))
        received_setup = col(row, idx("Received Setup Data?"))
        setup_date_received = col(row, idx("Date Recieved")) or col(row, idx("Date Received"))
        uploaded_portal = col(row, idx("Uploaded on Portal?"))
        uploaded_date = col(row, idx("Date "))
        received_item = col(row, idx("Received Item Data?"))
        item_date_received = col(row, idx("Date Received"))
        invoice_raised = col(row, idx("Invoice Raised?"))
        invoice_gen_date = col(row, idx("Invoice Generated Date"))
        final_payment = col(row, idx("Final Payment Received?"))
        final_payment_date = col(row, idx("Final Payment Received Date"))
        last_contacted = col(row, idx("Last Contacted On"))
        remarks = col(row, idx("Remarks"))

        ref_no = "IMP"
        lead_gen_ts = "NOW()"
        if lead_gen_date:
            iso = to_iso_date(lead_gen_date)
            if iso:
                lead_gen_ts = f"to_timestamp('{iso}', 'YYYY-MM-DD')"

        print(f"  -- {company_name} | {status} | {stage}")
        print(f"  ref_no := 'IMP' || LPAD(nextval('lead_import_ref_seq')::text, 4, '0');")
        print(f"  lead_gen_ts := {lead_gen_ts};")
        print(f"  poc_id := NULL;")
        if assigned_poc:
            print(f"  SELECT id INTO poc_id FROM public.user_profiles WHERE full_name = {escape_sql(assigned_poc)} LIMIT 1;")
        print(f"  INSERT INTO public.leads (company_name, stage, status, assigned_poc_id, reference_no, created_at)")
        print(f"  VALUES ({escape_sql(company_name)}, {escape_sql(stage)}, {escape_sql(status)}, poc_id, ref_no, lead_gen_ts)")
        print(f"  RETURNING id INTO lid;")
        # lead_details
        ld = []
        if person_name: ld.append(f"'person_name', {escape_sql(person_name)}")
        if mobile_number: ld.append(f"'mobile_number', {escape_sql(mobile_number)}")
        if email_id: ld.append(f"'email_id', {escape_sql(email_id)}")
        if lead_gen_date and to_iso_date(lead_gen_date): ld.append(f"'lead_generation_date', '{to_iso_date(lead_gen_date)}'")
        if lead_generated_by: ld.append(f"'lead_generated_by', {escape_sql(lead_generated_by)}")
        lead_details_json = "jsonb_build_object(" + ", ".join(ld) + ")" if ld else "'{}'::jsonb"
        print(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'lead_details', {lead_details_json});")
        # contacted
        ct = []
        if contacted_date and to_iso_date(contacted_date): ct.append(f"'contacted_date', '{to_iso_date(contacted_date)}'")
        if relevant: ct.append(f"'relevant', {escape_sql(relevant)}")
        if city: ct.append(f"'city', {escape_sql(city)}")
        if state: ct.append(f"'state', {escape_sql(state)}")
        if industry: ct.append(f"'industry', {escape_sql(industry)}")
        if no_of_divisions: ct.append(f"'no_of_divisions', {escape_sql(no_of_divisions)}")
        if name_of_divisions: ct.append(f"'name_of_divisions', {escape_sql(name_of_divisions)}")
        if designation: ct.append(f"'designation_of_person', {escape_sql(designation)}")
        if company_desc: ct.append(f"'company_description', {escape_sql(company_desc)}")
        if inventory_type: ct.append(f"'inventory_type_management_needed_for', {escape_sql(inventory_type)}")
        contacted_json = "jsonb_build_object(" + ", ".join(ct) + ")" if ct else "'{}'::jsonb"
        print(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'contacted', {contacted_json});")
        # brochure
        br = []
        if brochure_sent: br.append(f"'brochure_sent', {escape_sql(brochure_sent)}")
        if brochure_sent_date and to_iso_date(brochure_sent_date): br.append(f"'brochure_sent_date', '{to_iso_date(brochure_sent_date)}'")
        brochure_json = "jsonb_build_object(" + ", ".join(br) + ")" if br else "'{}'::jsonb"
        print(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'brochure', {brochure_json});")
        # demo_schedule
        ds = []
        if demo_finalized and to_iso_date(demo_finalized): ds.append(f"'date_finalized', '{to_iso_date(demo_finalized)}'")
        if demo_scheduled_date:
            dt_str = demo_scheduled_date + " " + demo_time if demo_time else demo_scheduled_date
            iso_dt = to_iso_date(demo_scheduled_date)
            if iso_dt and demo_time:
                ds.append(f"'demo_scheduled_datetime', '{iso_dt} {demo_time.strip()}'")
            elif iso_dt:
                ds.append(f"'demo_scheduled_datetime', '{iso_dt}'")
            else:
                ds.append(f"'demo_scheduled_datetime', {escape_sql(dt_str)}")
        if people_attending: ds.append(f"'people_attending', {escape_sql(people_attending)}")
        if roles_attendees: ds.append(f"'roles_of_attendees', {escape_sql(roles_attendees)}")
        if attendees_emails: ds.append(f"'attendees_emails', {escape_sql(attendees_emails)}")
        if attendees_mobile: ds.append(f"'attendees_mobile_no', {escape_sql(attendees_mobile)}")
        demo_sched_json = "jsonb_build_object(" + ", ".join(ds) + ")" if ds else "'{}'::jsonb"
        print(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'demo_schedule', {demo_sched_json});")
        # demo_completed
        dc = []
        if demo_status: dc.append(f"'demo_status', {escape_sql(demo_status)}")
        if demo_date and to_iso_date(demo_date): dc.append(f"'demo_date', '{to_iso_date(demo_date)}'")
        if demo_conducted_by: dc.append(f"'demo_conducted_by', {escape_sql(demo_conducted_by)}")
        if attendee_names: dc.append(f"'attendee_names', {escape_sql(attendee_names)}")
        if video_recorded: dc.append(f"'video_recorded', {escape_sql(video_recorded)}")
        if video_uploaded: dc.append(f"'video_uploaded', {escape_sql(video_uploaded)}")
        if demo_duration: dc.append(f"'demo_duration', {escape_sql(demo_duration)}")
        if interest_shown: dc.append(f"'interest_shown', {escape_sql(interest_shown)}")
        demo_comp_json = "jsonb_build_object(" + ", ".join(dc) + ")" if dc else "'{}'::jsonb"
        print(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'demo_completed', {demo_comp_json});")
        # offer_letter
        ol = []
        if offer_letter_sent: ol.append(f"'offer_letter_sent', {escape_sql(offer_letter_sent)}")
        if offer_letter_sent_date and to_iso_date(offer_letter_sent_date): ol.append(f"'offer_letter_sent_date', '{to_iso_date(offer_letter_sent_date)}'")
        if offer_letter_approved: ol.append(f"'offer_letter_approved', {escape_sql(offer_letter_approved)}")
        if offer_letter_approved_date and to_iso_date(offer_letter_approved_date): ol.append(f"'offer_letter_approved_date', '{to_iso_date(offer_letter_approved_date)}'")
        offer_json = "jsonb_build_object(" + ", ".join(ol) + ")" if ol else "'{}'::jsonb"
        print(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'offer_letter', {offer_json});")
        # po
        po = []
        if po_format_sent: po.append(f"'po_format_sent', {escape_sql(po_format_sent)}")
        if po_format_sent_date and to_iso_date(po_format_sent_date): po.append(f"'po_format_sent_date', '{to_iso_date(po_format_sent_date)}'")
        if po_received: po.append(f"'po_received', {escape_sql(po_received)}")
        if po_received_date and to_iso_date(po_received_date): po.append(f"'po_received_date', '{to_iso_date(po_received_date)}'")
        po_json = "jsonb_build_object(" + ", ".join(po) + ")" if po else "'{}'::jsonb"
        print(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'po', {po_json});")
        # performa_invoice
        pi = []
        if performa_sent: pi.append(f"'performa_invoice_sent', {escape_sql(performa_sent)}")
        if performa_sent_date and to_iso_date(performa_sent_date): pi.append(f"'performa_invoice_sent_date', '{to_iso_date(performa_sent_date)}'")
        if payment_received: pi.append(f"'payment_received', {escape_sql(payment_received)}")
        if payment_received_date and to_iso_date(payment_received_date): pi.append(f"'payment_received_date', '{to_iso_date(payment_received_date)}'")
        pi_json = "jsonb_build_object(" + ", ".join(pi) + ")" if pi else "'{}'::jsonb"
        print(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'performa_invoice', {pi_json});")
        # implementation_invoice
        impl = []
        if impl_sent: impl.append(f"'implementation_invoice_sent', {escape_sql(impl_sent)}")
        if impl_date_sent and to_iso_date(impl_date_sent): impl.append(f"'date_sent', '{to_iso_date(impl_date_sent)}'")
        impl_json = "jsonb_build_object(" + ", ".join(impl) + ")" if impl else "'{}'::jsonb"
        print(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'implementation_invoice', {impl_json});")
        # whatsapp_group
        wa = []
        if whatsapp_created: wa.append(f"'whatsapp_group_created', {escape_sql(whatsapp_created)}")
        if whatsapp_date and to_iso_date(whatsapp_date): wa.append(f"'date_created_on', '{to_iso_date(whatsapp_date)}'")
        wa_json = "jsonb_build_object(" + ", ".join(wa) + ")" if wa else "'{}'::jsonb"
        print(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'whatsapp_group', {wa_json});")
        # setup_data
        su = []
        if setup_sent: su.append(f"'setup_details_sent', {escape_sql(setup_sent)}")
        if setup_sent_date and to_iso_date(setup_sent_date): su.append(f"'sent_date', '{to_iso_date(setup_sent_date)}'")
        su_json = "jsonb_build_object(" + ", ".join(su) + ")" if su else "'{}'::jsonb"
        print(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'setup_data', {su_json});")
        # account_setup
        ac = []
        if received_setup: ac.append(f"'received_setup_data', {escape_sql(received_setup)}")
        if setup_date_received and to_iso_date(setup_date_received): ac.append(f"'date_received', '{to_iso_date(setup_date_received)}'")
        if uploaded_portal: ac.append(f"'uploaded_on_portal', {escape_sql(uploaded_portal)}")
        if uploaded_date and to_iso_date(uploaded_date): ac.append(f"'uploaded_date', '{to_iso_date(uploaded_date)}'")
        ac_json = "jsonb_build_object(" + ", ".join(ac) + ")" if ac else "'{}'::jsonb"
        print(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'account_setup', {ac_json});")
        # item_setup
        it = []
        if received_item: it.append(f"'received_item_data', {escape_sql(received_item)}")
        if item_date_received and to_iso_date(item_date_received): it.append(f"'date_received', '{to_iso_date(item_date_received)}'")
        it_json = "jsonb_build_object(" + ", ".join(it) + ")" if it else "'{}'::jsonb"
        print(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'item_setup', {it_json});")
        # first_invoice
        fi = []
        if invoice_raised: fi.append(f"'invoice_raised', {escape_sql(invoice_raised)}")
        if invoice_gen_date and to_iso_date(invoice_gen_date): fi.append(f"'invoice_generated_date', '{to_iso_date(invoice_gen_date)}'")
        fi_json = "jsonb_build_object(" + ", ".join(fi) + ")" if fi else "'{}'::jsonb"
        print(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'first_invoice', {fi_json});")
        # first_invoice_payment
        fp = []
        if final_payment: fp.append(f"'final_payment_received', {escape_sql(final_payment)}")
        if final_payment_date and to_iso_date(final_payment_date): fp.append(f"'final_payment_received_date', '{to_iso_date(final_payment_date)}'")
        fp_json = "jsonb_build_object(" + ", ".join(fp) + ")" if fp else "'{}'::jsonb"
        print(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'first_invoice_payment', {fp_json});")
        # final_closing (Last Contacted On, Remarks)
        fc = []
        if last_contacted and to_iso_date(last_contacted): fc.append(f"'last_contact_date', '{to_iso_date(last_contacted)}'")
        if remarks: fc.append(f"'remark', {escape_sql(remarks)}")
        fc_json = "jsonb_build_object(" + ", ".join(fc) + ")" if fc else "'{}'::jsonb"
        print(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'final_closing', {fc_json});")
        print("")
    print("END $$;")
    print("\n-- Done. Check public.leads and public.lead_stage_data.")

if __name__ == "__main__":
    main()
