-- ============================================================================
-- Pages Master: Replace all pages with the Support form page list
-- Run in Supabase SQL Editor. This clears ticket page references, DELETES existing
-- pages, then INSERTs the new list. (Required: clear page_id first to avoid FK error.)
-- ============================================================================

-- 1) Clear page_id on all tickets so we can delete pages (avoids foreign key error)
UPDATE public.tickets SET page_id = NULL WHERE page_id IS NOT NULL;

-- 2) Delete all existing pages
DELETE FROM public.pages;

-- 3) Insert new page names (one per row for Support form "Page" dropdown)
INSERT INTO public.pages (name) VALUES
('Approvals'),
('Budget Report'),
('Bill Register'),
('Company Division Wise Stock Movement Summary'),
('Company Wise Approved Quotes'),
('Cost Center'),
('Cost Center Wise Consumption'),
('Cost Centre Excess Consumption Report'),
('Cost Centre History Report'),
('Create Indent'),
('Create Item'),
('Create Po'),
('Create Wo'),
('Create Department'),
('Create Wo Indent'),
('Dashboard'),
('Department Wise Consumption Report'),
('Division'),
('Enquries'),
('EMS Dashboard'),
('Furnace'),
('Gate Entry'),
('Gate Entry Register'),
('GRN Approval'),
('GRN Entry'),
('GRN Made But Not Issued Report'),
('GRN Register'),
('Indent MIS Register'),
('Indent Register'),
('Indents to Approve'),
('Issue'),
('Issue Approval'),
('Issue Approve'),
('Issue Register'),
('Issue Return Register'),
('Issue Tools on Returnable Basis'),
('ITEM'),
('Item Group Wise Consumption'),
('Item Purchase History Report'),
('Item Search'),
('Item Stock'),
('Item Summary'),
('Items Pending to be sent for repair'),
('Login'),
('Monthly Budget'),
('Monthly Purchase Saving Report'),
('Non-returnable Gate Pass'),
('Non-returnable Goods Register'),
('Notifications'),
('Payment Sheet'),
('Pending Bills'),
('Pending Bills to Approve'),
('Pending for Tally Entry'),
('Pending Indent RFQ'),
('Pending PO (GRN)'),
('Pending Work Order Indent RFQ'),
('Pending Work Orders (WRN)'),
('Physical Stock Taking'),
('Pick Quotes'),
('PO Audit Report'),
('PO Register'),
('POs To Approve'),
('Purchase Central'),
('Purchase Return Register'),
('Physical stocks to approve'),
('Quotation Audit Report'),
('Quotation Comparison'),
('Quotations'),
('Reorder Level'),
('RFQ Mail'),
('Reorder level crossed'),
('Reports'),
('Returnable Gate Pass'),
('Returnable Goods Register'),
('Returnable Items Not Yet Received'),
('RFQ'),
('Set Up'),
('Stock Adjustment'),
('Stock Adjustment Approvals'),
('Stock Adjustment Register'),
('Stock Ledger'),
('Stock Summary'),
('Stock Transfer'),
('Tag Vendor'),
('Tag For GRN'),
('Users'),
('Vendor Quote'),
('Vendor Summary Report'),
('Vendors'),
('Vendors to Approve'),
('Vendor GRN History report'),
('Vendor Purchase History report'),
('Whatsapp IndustryPrime'),
('Work Order Indent'),
('Work Order Indents to Approve'),
('Work Order Indent Register'),
('Work Order Register'),
('WRN Entry'),
('WRN Register');
