#!/usr/bin/env python3
"""
Generate SQL to import leads from a tab-separated (TSV) sheet into public.leads and
public.lead_stage_data. This populates lead_details and contacted (and optional stages)
so Person Name, City, State etc. show correctly in the app.

Usage:
  python database/tsv_to_lead_import_sql.py < leads.tsv > IMPORT_LEADS_NEW.sql
  # Or:
  python database/tsv_to_lead_import_sql.py leads.tsv -o IMPORT_LEADS_NEW.sql

Sheet column order (0-based; adjust COLS if your sheet differs):
  0: Company Name
  1: Status (Open/Closed)
  2: Stage (Lead, Contacted, Brochure, Demo Schedule, Demo Completed, Quotation, PO, ...)
  3: POC (Assigned POC full name, e.g. Shubham Kejriwal)
  4: Person Name
  5: Mobile Number
  6: Email ID
  7: Lead Generation Date (DD/MM/YYYY)
  8: Lead Generated By
  9: (optional) Contacted Date (DD/MM/YYYY)
  10: Relevant? (Yes/No/Maybe)
  11: City
  12: State
  13: Industry
  14: No of Divisions
  15: Name of Divisions
  16: Designation of Person
  17: Company Description
  18: Inventory Type Management Needed For?
  ... (later columns: brochure, demo schedule, demo completed, etc.)
  last column: Remark (final_closing.remark)
"""

import re
import sys
from pathlib import Path

# 0-based column indices for your sheet (adjust to match your export)
COLS = {
    "company_name": 0,
    "status": 1,
    "stage": 2,
    "poc_name": 3,
    "person_name": 4,
    "mobile_number": 5,
    "email_id": 6,
    "lead_generation_date": 7,
    "lead_generated_by": 8,
    "contacted_date": 9,
    "relevant": 10,
    "city": 11,
    "state": 12,
    "industry": 13,
    "no_of_divisions": 14,
    "name_of_divisions": 15,
    "designation_of_person": 16,
    "company_description": 17,
    "inventory_type_management_needed_for": 18,
    "brochure_sent": 19,
    "brochure_sent_date": 20,
    "date_finalized": 21,
    "demo_scheduled_date": 22,
    "demo_scheduled_time": 23,
    "people_attending": 24,
    "roles_of_attendees": 25,
    "attendees_emails": 26,
    "attendees_mobile_no": 27,
    "demo_status": 28,
    "demo_date": 29,
    "attendee_names": 30,
    "video_recorded": 31,
    "video_uploaded": 32,
    "demo_duration": 33,
    "interest_shown": 34,
    "remark": -1,  # last column
}


def esc(s: str) -> str:
    """Escape for SQL single-quoted string (double single quotes)."""
    if s is None:
        return ""
    return str(s).replace("'", "''").strip()


def parse_date_ddmmyyyy(s: str) -> str | None:
    """Convert DD/MM/YYYY to YYYY-MM-DD, or return None if invalid."""
    if not s or not s.strip():
        return None
    s = s.strip()
    m = re.match(r"(\d{1,2})/(\d{1,2})/(\d{4})", s)
    if m:
        d, mo, y = m.group(1), m.group(2), m.group(3)
        return f"{y}-{int(mo):02d}-{int(d):02d}"
    return None


def get(row: list[str], col: int) -> str:
    if col < 0:
        col = len(row) + col  # -1 = last
    if 0 <= col < len(row) and row[col].strip():
        return row[col].strip()
    return ""


def build_jsonb_pairs(keys_values: list[tuple[str, str]]) -> str:
    """Build jsonb_build_object('k1','v1','k2','v2') with escaping."""
    parts = []
    for k, v in keys_values:
        if v is None:
            v = ""
        v = esc(v)
        parts.append(f"'{k}', '{v}'")
    return "jsonb_build_object(" + ", ".join(parts) + ")"


def main() -> None:
    if len(sys.argv) >= 2 and sys.argv[1] != "-o":
        input_path = Path(sys.argv[1])
        if not input_path.exists():
            print("Usage: python tsv_to_lead_import_sql.py [input.tsv] [-o output.sql]", file=sys.stderr)
            sys.exit(1)
        lines = input_path.read_text(encoding="utf-8", errors="replace").splitlines()
    else:
        lines = sys.stdin.read().splitlines()

    out_path = None
    if "-o" in sys.argv:
        i = sys.argv.index("-o")
        if i + 1 < len(sys.argv):
            out_path = Path(sys.argv[i + 1])

    rows = []
    for line in lines:
        line = line.strip()
        if not line:
            continue
        row = [cell.strip() for cell in line.split("\t")]
        if len(row) < 5:
            continue
        rows.append(row)

    if not rows:
        print("No rows to import.", file=sys.stderr)
        sys.exit(0)

    c = COLS
    sql_lines = [
        "-- Generated by tsv_to_lead_import_sql.py – import into public.leads + lead_stage_data",
        "-- Run in Supabase SQL Editor. Requires public.user_profiles (full_name).",
        "",
        "CREATE SEQUENCE IF NOT EXISTS lead_import_ref_seq START 1;",
        "",
        "DO $$",
        "DECLARE",
        "  lid UUID;",
        "  ref_no TEXT;",
        "  lead_gen_ts TIMESTAMPTZ;",
        "  poc_id UUID;",
        "  r TEXT[];",
        "  i INT := 1;",
        "BEGIN",
    ]

    for row in rows:
        company = get(row, c["company_name"])
        if not company:
            continue
        status = get(row, c["status"]) or "Open"
        if status not in ("Open", "Closed"):
            status = "Open"
        stage = get(row, c["stage"]) or "Lead"
        poc_name = get(row, c["poc_name"])
        person_name = get(row, c["person_name"])
        mobile = get(row, c["mobile_number"])
        email = get(row, c["email_id"])
        lead_gen_date = parse_date_ddmmyyyy(get(row, c["lead_generation_date"]))
        lead_generated_by = get(row, c["lead_generated_by"])
        contacted_date = parse_date_ddmmyyyy(get(row, c["contacted_date"])) or lead_gen_date
        relevant = get(row, c["relevant"])
        city = get(row, c["city"])
        state = get(row, c["state"])
        industry = get(row, c["industry"])
        no_div = get(row, c["no_of_divisions"])
        name_div = get(row, c["name_of_divisions"])
        designation = get(row, c["designation_of_person"])
        company_desc = get(row, c["company_description"])
        inv_type = get(row, c["inventory_type_management_needed_for"])
        brochure_sent = get(row, c["brochure_sent"])
        brochure_date = parse_date_ddmmyyyy(get(row, c["brochure_sent_date"]))
        date_finalized = parse_date_ddmmyyyy(get(row, c["date_finalized"]))
        demo_date_str = parse_date_ddmmyyyy(get(row, c["demo_scheduled_date"]))
        demo_time = get(row, c["demo_scheduled_time"])
        demo_datetime = f"{demo_date_str} {demo_time}" if demo_date_str and demo_time else (demo_date_str or "")
        people_att = get(row, c["people_attending"])
        roles_att = get(row, c["roles_of_attendees"])
        att_emails = get(row, c["attendees_emails"])
        att_mobile = get(row, c["attendees_mobile_no"])
        demo_status = get(row, c["demo_status"])
        demo_date_done = parse_date_ddmmyyyy(get(row, c["demo_date"]))
        attendee_names = get(row, c["attendee_names"])
        video_rec = get(row, c["video_recorded"])
        video_up = get(row, c["video_uploaded"])
        demo_dur = get(row, c["demo_duration"])
        interest = get(row, c["interest_shown"])
        remark = get(row, c["remark"])

        lead_gen_ts = f"to_timestamp('{lead_gen_date}', 'YYYY-MM-DD')" if lead_gen_date else "NOW()"

        sql_lines.append(f"  -- {company} | {status} | {stage}")
        sql_lines.append("  ref_no := 'IMP' || LPAD(nextval('lead_import_ref_seq')::text, 4, '0');")
        sql_lines.append(f"  lead_gen_ts := {lead_gen_ts};")
        sql_lines.append("  poc_id := NULL;")
        if poc_name:
            sql_lines.append(f"  SELECT id INTO poc_id FROM public.user_profiles WHERE full_name = '{esc(poc_name)}' LIMIT 1;")
        sql_lines.append(
            f"  INSERT INTO public.leads (company_name, stage, status, assigned_poc_id, reference_no, created_at)"
        )
        sql_lines.append(f"  VALUES ('{esc(company)}', '{esc(stage)}', '{esc(status)}', poc_id, ref_no, lead_gen_ts)")
        sql_lines.append("  RETURNING id INTO lid;")

        # lead_details
        lead_detail_pairs = [
            ("person_name", person_name),
            ("mobile_number", mobile),
            ("email_id", email),
            ("lead_generation_date", lead_gen_date or ""),
            ("lead_generated_by", lead_generated_by),
        ]
        lead_detail_pairs = [(k, v) for k, v in lead_detail_pairs if v]
        if lead_detail_pairs:
            obj = build_jsonb_pairs(lead_detail_pairs)
            sql_lines.append(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'lead_details', {obj});")
        else:
            sql_lines.append("  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'lead_details', '{}'::jsonb);")

        # contacted
        contacted_pairs = [
            ("contacted_date", contacted_date),
            ("relevant", relevant),
            ("city", city),
            ("state", state),
            ("industry", industry),
            ("no_of_divisions", no_div),
            ("name_of_divisions", name_div),
            ("designation_of_person", designation),
            ("company_description", company_desc),
            ("inventory_type_management_needed_for", inv_type),
        ]
        contacted_pairs = [(k, v) for k, v in contacted_pairs if v]
        if contacted_pairs:
            obj = build_jsonb_pairs(contacted_pairs)
            sql_lines.append(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'contacted', {obj});")
        else:
            sql_lines.append("  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'contacted', '{}'::jsonb);")

        # brochure
        brochure_pairs = [("brochure_sent", brochure_sent), ("brochure_sent_date", brochure_date or "")]
        brochure_pairs = [(k, v) for k, v in brochure_pairs if v]
        if brochure_pairs:
            obj = build_jsonb_pairs(brochure_pairs)
            sql_lines.append(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'brochure', {obj});")
        else:
            sql_lines.append("  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'brochure', '{}'::jsonb);")

        # demo_schedule
        demo_sched_pairs = [
            ("date_finalized", date_finalized or ""),
            ("demo_scheduled_datetime", demo_datetime),
            ("people_attending", people_att),
            ("roles_of_attendees", roles_att),
            ("attendees_emails", att_emails),
            ("attendees_mobile_no", att_mobile),
        ]
        demo_sched_pairs = [(k, v) for k, v in demo_sched_pairs if v]
        if demo_sched_pairs:
            obj = build_jsonb_pairs(demo_sched_pairs)
            sql_lines.append(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'demo_schedule', {obj});")
        else:
            sql_lines.append("  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'demo_schedule', '{}'::jsonb);")

        # demo_completed
        demo_done_pairs = [
            ("demo_status", demo_status),
            ("demo_date", demo_date_done or ""),
            ("attendee_names", attendee_names),
            ("video_recorded", video_rec),
            ("video_uploaded", video_up),
            ("demo_duration", demo_dur),
            ("interest_shown", interest),
        ]
        demo_done_pairs = [(k, v) for k, v in demo_done_pairs if v]
        if demo_done_pairs:
            obj = build_jsonb_pairs(demo_done_pairs)
            sql_lines.append(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'demo_completed', {obj});")
        else:
            sql_lines.append("  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'demo_completed', '{}'::jsonb);")

        for slug in ["offer_letter", "po", "performa_invoice", "implementation_invoice", "whatsapp_group", "setup_data", "account_setup", "item_setup", "first_invoice", "first_invoice_payment"]:
            sql_lines.append(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, '{slug}', '{{}}'::jsonb);")

        if remark:
            remark_esc = esc(remark)
            sql_lines.append(f"  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'final_closing', jsonb_build_object('remark', '{remark_esc}'));")
        else:
            sql_lines.append("  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data) VALUES (lid, 'final_closing', '{}'::jsonb);")

        sql_lines.append("")

    sql_lines.append("END $$;")

    out = "\n".join(sql_lines)
    if out_path:
        out_path.write_text(out, encoding="utf-8")
        print(f"Wrote {len(rows)} leads to {out_path}", file=sys.stderr)
    else:
        print(out)


if __name__ == "__main__":
    main()
