-- =============================================================================
-- Client to Lead — full export (SELECT) and bulk update patterns
-- Tables: public.leads, public.lead_stage_data (data JSONB per stage_slug),
--         public.user_profiles (assigned_poc_id → full_name)
-- Stage slugs match fms-frontend/src/pages/Leads/leadStageFields.tsx
-- =============================================================================
-- NOTE: Full 74-column layout matches LeadImportPage.tsx COLS and leadStageFields.tsx
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1) FULL EXPORT — one row per lead (74 logical columns, same order as import sheet)
--    Invalid/missing date strings may need NULLIF in production; cast errors = fix data.
-- ---------------------------------------------------------------------------
SELECT
  l.company_name AS "Company Name",
  l.status AS "Status",
  l.stage AS "Stage",
  poc.full_name AS "Assigned POC",
  ld_lead.data ->> 'person_name' AS "Person Name",
  ld_lead.data ->> 'mobile_number' AS "Mobile Number",
  ld_lead.data ->> 'email_id' AS "Email ID",
  to_char((ld_lead.data ->> 'lead_generation_date')::date, 'DD/MM/YYYY') AS "Lead Generation Date",
  ld_lead.data ->> 'lead_generated_by' AS "Lead Generated By",
  to_char((ld_cont.data ->> 'contacted_date')::date, 'DD/MM/YYYY') AS "Contacted Date",
  ld_cont.data ->> 'relevant' AS "Relevant?",
  ld_cont.data ->> 'city' AS "City",
  ld_cont.data ->> 'state' AS "State",
  ld_cont.data ->> 'industry' AS "Industry",
  ld_cont.data ->> 'no_of_divisions' AS "No of Divisions",
  ld_cont.data ->> 'name_of_divisions' AS "Name of Divisions",
  ld_cont.data ->> 'designation_of_person' AS "Designation of Person",
  ld_cont.data ->> 'company_description' AS "Company Description",
  ld_cont.data ->> 'inventory_type_management_needed_for' AS "Inventory Type Management Needed for?",
  ld_bro.data ->> 'brochure_sent' AS "Brochure Sent?",
  to_char((ld_bro.data ->> 'brochure_sent_date')::date, 'DD/MM/YYYY') AS "Brochure Sent Date",
  to_char((ld_dsched.data ->> 'date_finalized')::date, 'DD/MM/YYYY') AS "Date On which Demo Schedule was finalized?",
  split_part(COALESCE(ld_dsched.data ->> 'demo_scheduled_datetime', ''), ' ', 1) AS "Demo Scheduled Date",
  split_part(COALESCE(ld_dsched.data ->> 'demo_scheduled_datetime', ' '), ' ', 2) AS "Demo Time",
  ld_dsched.data ->> 'people_attending' AS "People Attending",
  ld_dsched.data ->> 'roles_of_attendees' AS "Roles of Attendees",
  ld_dsched.data ->> 'attendees_emails' AS "Attendees Emails",
  ld_dsched.data ->> 'attendees_mobile_no' AS "Attendees Mobile No",
  ld_demo.data ->> 'demo_status' AS "Demo Status",
  to_char((ld_demo.data ->> 'demo_date')::date, 'DD/MM/YYYY') AS "Demo Date",
  ld_demo.data ->> 'demo_conducted_by' AS "Demo Conducted By",
  ld_demo.data ->> 'attendee_names' AS "Attendee Names",
  ld_demo.data ->> 'video_recorded' AS "Video Recorded",
  ld_demo.data ->> 'video_uploaded' AS "Video Uploaded",
  ld_demo.data ->> 'demo_duration' AS "Demo Duration",
  ld_demo.data ->> 'interest_shown' AS "Interest Shown",
  ld_gf.data ->> 'google_form_sent' AS "Google Form Sent?",
  to_char((ld_gf.data ->> 'google_form_sent_date')::date, 'DD/MM/YYYY') AS "Google Form Sent Date",
  ld_gf.data ->> 'google_form_filled' AS "Google Form Filled",
  to_char((ld_gf.data ->> 'google_form_filled_date')::date, 'DD/MM/YYYY') AS "Google Form Filled Date",
  ld_off.data ->> 'offer_letter_sent' AS "Offer Letter Sent?",
  to_char((ld_off.data ->> 'offer_letter_sent_date')::date, 'DD/MM/YYYY') AS "Offer Letter Sent Date",
  ld_off.data ->> 'offer_letter_approved' AS "Offer Letter Approved?",
  to_char((ld_off.data ->> 'offer_letter_approved_date')::date, 'DD/MM/YYYY') AS "Offer Letter Approved Date",
  ld_po.data ->> 'po_format_sent' AS "PO Format Sent?",
  to_char((ld_po.data ->> 'po_format_sent_date')::date, 'DD/MM/YYYY') AS "PO Format Sent Date",
  ld_po.data ->> 'po_received' AS "PO Recieved?",
  to_char((ld_po.data ->> 'po_received_date')::date, 'DD/MM/YYYY') AS "PO Received Date",
  ld_pi.data ->> 'performa_invoice_sent' AS "Performa Invoice Sent?",
  to_char((ld_pi.data ->> 'performa_invoice_sent_date')::date, 'DD/MM/YYYY') AS "Performa Invoice Sent Date",
  ld_pi.data ->> 'payment_received' AS "Payment Received?",
  to_char((ld_pi.data ->> 'payment_received_date')::date, 'DD/MM/YYYY') AS "Payment Received Date.",
  ld_impl.data ->> 'implementation_invoice_sent' AS "Implementation Invoice Sent?",
  to_char((ld_impl.data ->> 'date_sent')::date, 'DD/MM/YYYY') AS "Date Sent",
  ld_wa.data ->> 'whatsapp_group_created' AS "WhatsApp Group Created",
  to_char((ld_wa.data ->> 'date_created_on')::date, 'DD/MM/YYYY') AS "Date Created on?",
  ld_setup.data ->> 'setup_details_sent' AS "Setup Details Sent?",
  to_char((ld_setup.data ->> 'sent_date')::date, 'DD/MM/YYYY') AS "Sent Date",
  ld_acc.data ->> 'received_setup_data' AS "Received Setup Data?",
  to_char((ld_acc.data ->> 'date_received')::date, 'DD/MM/YYYY') AS "Date Recieved",
  ld_acc.data ->> 'uploaded_on_portal' AS "Uploaded on Portal?",
  to_char((ld_acc.data ->> 'uploaded_date')::date, 'DD/MM/YYYY') AS "Date",
  ld_item.data ->> 'received_item_data' AS "Received Item Data?",
  to_char((ld_item.data ->> 'date_received')::date, 'DD/MM/YYYY') AS "Date Received",
  ld_item.data ->> 'uploaded_on_portal' AS "Uploaded on Portal? -1",
  to_char((ld_item.data ->> 'upload_date')::date, 'DD/MM/YYYY') AS "Upload Date",
  to_char((ld_tr.data ->> 'start_date')::date, 'DD/MM/YYYY') AS "Start Date",
  to_char((ld_tr.data ->> 'end_date')::date, 'DD/MM/YYYY') AS "End Date",
  ld_tr.data ->> 'f_status' AS "FStatus",
  ld_fi.data ->> 'invoice_raised' AS "Invoice Raised?",
  to_char((ld_fi.data ->> 'invoice_generated_date')::date, 'DD/MM/YYYY') AS "Invoice Generated Date",
  ld_fip.data ->> 'final_payment_received' AS "Final Payment Received?",
  to_char((ld_fip.data ->> 'final_payment_received_date')::date, 'DD/MM/YYYY') AS "Final Payment Received Date",
  to_char((ld_fc.data ->> 'last_contact_date')::date, 'DD/MM/YYYY') AS "Last Contacted On",
  l.reference_no
FROM public.leads l
LEFT JOIN public.user_profiles poc ON poc.id = l.assigned_poc_id
LEFT JOIN public.lead_stage_data ld_lead ON ld_lead.lead_id = l.id AND ld_lead.stage_slug = 'lead_details'
LEFT JOIN public.lead_stage_data ld_cont ON ld_cont.lead_id = l.id AND ld_cont.stage_slug = 'contacted'
LEFT JOIN public.lead_stage_data ld_bro ON ld_bro.lead_id = l.id AND ld_bro.stage_slug = 'brochure'
LEFT JOIN public.lead_stage_data ld_dsched ON ld_dsched.lead_id = l.id AND ld_dsched.stage_slug = 'demo_schedule'
LEFT JOIN public.lead_stage_data ld_demo ON ld_demo.lead_id = l.id AND ld_demo.stage_slug = 'demo_completed'
LEFT JOIN public.lead_stage_data ld_gf ON ld_gf.lead_id = l.id AND ld_gf.stage_slug = 'google_form'
LEFT JOIN public.lead_stage_data ld_off ON ld_off.lead_id = l.id AND ld_off.stage_slug = 'offer_letter'
LEFT JOIN public.lead_stage_data ld_po ON ld_po.lead_id = l.id AND ld_po.stage_slug = 'po'
LEFT JOIN public.lead_stage_data ld_pi ON ld_pi.lead_id = l.id AND ld_pi.stage_slug = 'performa_invoice'
LEFT JOIN public.lead_stage_data ld_impl ON ld_impl.lead_id = l.id AND ld_impl.stage_slug = 'implementation_invoice'
LEFT JOIN public.lead_stage_data ld_wa ON ld_wa.lead_id = l.id AND ld_wa.stage_slug = 'whatsapp_group'
LEFT JOIN public.lead_stage_data ld_setup ON ld_setup.lead_id = l.id AND ld_setup.stage_slug = 'setup_data'
LEFT JOIN public.lead_stage_data ld_acc ON ld_acc.lead_id = l.id AND ld_acc.stage_slug = 'account_setup'
LEFT JOIN public.lead_stage_data ld_item ON ld_item.lead_id = l.id AND ld_item.stage_slug = 'item_setup'
LEFT JOIN public.lead_stage_data ld_tr ON ld_tr.lead_id = l.id AND ld_tr.stage_slug = 'training_stage'
LEFT JOIN public.lead_stage_data ld_fi ON ld_fi.lead_id = l.id AND ld_fi.stage_slug = 'first_invoice'
LEFT JOIN public.lead_stage_data ld_fip ON ld_fip.lead_id = l.id AND ld_fip.stage_slug = 'first_invoice_payment'
LEFT JOIN public.lead_stage_data ld_fc ON ld_fc.lead_id = l.id AND ld_fc.stage_slug = 'final_closing'
ORDER BY l.reference_no DESC;


-- ---------------------------------------------------------------------------
-- 2) OPTIONAL: save as a view for repeated exports
-- ---------------------------------------------------------------------------
-- CREATE OR REPLACE VIEW public.v_leads_client_to_lead_flat AS
-- SELECT ... (same as above without ORDER BY, or with ORDER BY inside view);
-- GRANT SELECT ON public.v_leads_client_to_lead_flat TO authenticated;


-- ---------------------------------------------------------------------------
-- 3) UPDATE PATTERN — update one lead by reference_no (repeat / script from sheet)
--    Dates in JSONB must be YYYY-MM-DD strings (same as the app).
--    Replace placeholders below.
-- ---------------------------------------------------------------------------

-- 3a) Core lead row (status, stage, POC by name)
/*
UPDATE public.leads l
SET
  status = 'Open',   -- or 'Closed'
  stage = 'Demo Completed',
  assigned_poc_id = (SELECT id FROM public.user_profiles WHERE full_name = 'Shubham Kejriwal' LIMIT 1)
WHERE l.reference_no = 'DEMO0123';
*/

-- 3b) Merge JSONB stage data (upsert row if missing)
--     Use jsonb_strip_nulls so you can omit keys you do not want to change.

/*
INSERT INTO public.lead_stage_data (lead_id, stage_slug, data, updated_at)
SELECT l.id, 'contacted', '{}'::jsonb, now()
FROM public.leads l
WHERE l.reference_no = 'DEMO0123'
ON CONFLICT (lead_id, stage_slug) DO NOTHING;

UPDATE public.lead_stage_data lsd
SET
  data = lsd.data
    || jsonb_build_object(
      'contacted_date', '2025-06-06',
      'city', 'Jamshedpur',
      'state', 'Jharkhand',
      'industry', 'Fastners',
      'no_of_divisions', '1',
      'name_of_divisions', 'Fastners'
    ),
  updated_at = now()
FROM public.leads l
WHERE lsd.lead_id = l.id
  AND l.reference_no = 'DEMO0123'
  AND lsd.stage_slug = 'contacted';
*/

-- Example: brochure + demo_completed in one transaction
/*
UPDATE public.lead_stage_data lsd
SET data = lsd.data || jsonb_build_object(
    'brochure_sent', 'Yes',
    'brochure_sent_date', '2025-06-12'
  ), updated_at = now()
FROM public.leads l
WHERE lsd.lead_id = l.id AND l.reference_no = 'DEMO0123' AND lsd.stage_slug = 'brochure';

UPDATE public.lead_stage_data lsd
SET data = lsd.data || jsonb_build_object(
    'demo_status', 'Done',
    'demo_date', '2025-06-06'
  ), updated_at = now()
FROM public.leads l
WHERE lsd.lead_id = l.id AND l.reference_no = 'DEMO0123' AND lsd.stage_slug = 'demo_completed';
*/


-- ---------------------------------------------------------------------------
-- 4) HELPER: merge arbitrary patch for one stage (safe for missing row)
--    Call: SELECT merge_lead_stage_by_ref('DEMO0123', 'po', '{"po_format_sent":"Yes","po_format_sent_date":"2025-07-24"}'::jsonb);
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.merge_lead_stage_by_ref(
  p_reference_no text,
  p_stage_slug text,
  p_patch jsonb
) RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
  v_lead_id uuid;
BEGIN
  SELECT id INTO v_lead_id FROM public.leads WHERE reference_no = p_reference_no LIMIT 1;
  IF v_lead_id IS NULL THEN
    RAISE EXCEPTION 'Lead not found: %', p_reference_no;
  END IF;

  INSERT INTO public.lead_stage_data (lead_id, stage_slug, data, updated_at)
  VALUES (v_lead_id, p_stage_slug, jsonb_strip_nulls(p_patch), now())
  ON CONFLICT (lead_id, stage_slug)
  DO UPDATE SET
    data = public.lead_stage_data.data || EXCLUDED.data,
    updated_at = now();
END;
$$;

-- Example:
-- SELECT merge_lead_stage_by_ref('DEMO0001', 'first_invoice_payment',
--   '{"final_payment_received":"Yes","final_payment_received_date":"2025-07-31"}'::jsonb);


-- ---------------------------------------------------------------------------
-- 5) Bulk update from a staging table (recommended for large imports)
--    1) Create temp/staging table with columns matching your CSV.
--    2) COPY or INSERT rows.
--    3) Join staging → leads by company_name or reference_no and UPDATE.
-- ---------------------------------------------------------------------------

/*
CREATE TEMP TABLE stg_leads (
  reference_no text,
  company_name text,
  status text,
  stage text,
  poc_name text,
  -- add more columns as needed
  contacted_date text,
  city text,
  state text
);

-- COPY stg_leads FROM STDIN WITH (FORMAT csv, HEADER true);

UPDATE public.leads l
SET
  status = s.status,
  stage = s.stage,
  assigned_poc_id = up.id
FROM stg_leads s
LEFT JOIN public.user_profiles up ON up.full_name = s.poc_name
WHERE l.reference_no = s.reference_no;

UPDATE public.lead_stage_data lsd
SET
  data = lsd.data || jsonb_build_object(
    'contacted_date', NULLIF(trim(s.contacted_date), '')::date::text,
    'city', NULLIF(trim(s.city), ''),
    'state', NULLIF(trim(s.state), '')
  ),
  updated_at = now()
FROM public.leads l
JOIN stg_leads s ON s.reference_no = l.reference_no
WHERE lsd.lead_id = l.id AND lsd.stage_slug = 'contacted';
*/


-- ---------------------------------------------------------------------------
-- 6) Optional: store “Google Form” columns until UI exists (final_closing JSON)
-- ---------------------------------------------------------------------------
-- SELECT merge_lead_stage_by_ref('DEMO0001', 'final_closing',
--   '{"remark":"Google Form: Yes, 2025-08-01"}'::jsonb);
